@startuml instant_config_data_layer_class_diagram

package common.domain.repository {
    interface InstantConfigRepository {}
}

package common.domain.entities {
    class InstantConfig {}
}

package common.data {
    package repository {
        class FirestoreInstantConfigRepository {}
    }

    package models {
        class InstantConfigData {
            + toJson()
            + factory fromJson()
        }
    }
}

package core.src.data.model {
    class DataModel {}
}

FirestoreInstantConfigRepository ..|> InstantConfigRepository
FirestoreInstantConfigRepository --> InstantConfigData : uses

InstantConfigData --> InstantConfig
InstantConfigData ..|> DataModel

@enduml
