@startuml
skinparam ParticipantPadding 20
    skinparam BoxPadding 10

    actor Bob

    participant RouteInformationProvider << (C,#ADD1B2) >>
    participant Router << (C,#ADD1B2) >>
    participant RouteInformationParser << (C,#ADD1B2) >>
    participant RouterDelegate << (C,#ADD1B2) >>
    participant AppState << (C,#ADD1B2) >>

    ' User changes page using the UI.

    Bob -> RouteInformationProvider : Enter URL in Browser
    activate RouteInformationProvider
    RouteInformationProvider -> Router : notifyListeners()
    deactivate RouteInformationProvider
    activate Router
    Router -> RouteInformationParser : parseRouteInformation()
    deactivate Router
    activate RouteInformationParser
    RouteInformationParser -> RouterDelegate : setNewRoutePath()
    deactivate RouteInformationParser
    activate RouterDelegate
    RouterDelegate -> Router : notifyListeners()
    RouterDelegate -> AppState : build()
    AppState -> RouterDelegate : Navigator.push()
    deactivate RouterDelegate
@enduml