@startuml
package common.presentation.routes {

        class MetricsRouteInformationParser{
            Future parseRouteInformation()
            RouteInformation restoreRouteInformation()
        }

        class MetricsRouterDelegate{

            Widget build()
            Future<void> setNewRoutePath()
        }
        class MetricsPageGenerator{
            static MaterialPage generatePage()
        }

}

MetricsRouterDelegate --* ChangeNotifier : with
MetricsRouterDelegate --* PopNavigatorRouterDelegateMixin : with
MetricsRouterDelegate --> MetricsPageGenerator : uses
MaterialApp.router --> MetricsRouterDelegate : uses
MaterialApp.router --> MetricsRouteInformationParser :uses
@enduml