@startuml
skinparam ParticipantPadding 20
    skinparam BoxPadding 10

    actor Bob

    participant UI << (C,#ADD1B2) >>
    participant RouteInformationProvider << (C,#ADD1B2) >>
    participant RouteInformationParser << (C,#ADD1B2) >>
    participant RouterDelegate << (C,#ADD1B2) >>
    participant Router << (C,#ADD1B2) >>
    participant AppState << (C,#ADD1B2) >>

    ' User changes page using the UI.

    Bob -> UI : Open new page
    activate UI
    UI -> RouteInformationProvider : New intent
    deactivate UI
    activate RouteInformationProvider
    RouteInformationProvider -> RouteInformationParser : Call
    deactivate RouteInformationProvider
    activate RouteInformationParser
    RouteInformationParser -> RouterDelegate : Set new Route
    deactivate RouteInformationParser
    activate RouterDelegate
    RouterDelegate -> Router : Rebuild
    Router -> RouterDelegate : Obtain newly configured Navigator for rebuild
    RouterDelegate -> AppState : Modifies based on system notifications
    AppState -> RouterDelegate : Request changes to navigator
    deactivate RouterDelegate
@enduml