source:
  buildkite:
    access_token: $BUILDKITE_TOKEN
    pipeline_slug: ci-integrations-pipeline
    organization_slug: metrics
destination:
  firestore:
    firebase_project_id: metrics-d9c67
    firebase_user_email: $WEB_APP_USER_EMAIL
    firebase_user_pass: $WEB_APP_USER_PASSWORD
    firebase_public_api_key: AIzaSyCkM-7WEAb9GGCjKQNChi5MD2pqrcRanzo
    metrics_project_id: buildkite_ci_integrations
