source:
  buildkite:
    access_token: $BUILDKITE_TOKEN
    pipeline_slug: $PIPELINE_SLUG
    organization_slug: metrics
destination:
  firestore:
    firebase_project_id: metrics-d9c67
    firebase_user_email: $WEB_APP_USER_EMAIL
    firebase_user_pass: $WEB_APP_USER_PASSWORD
    firebase_public_api_key: $CI_INTEGRATIONS_FIREBASE_API_KEY
    metrics_project_id: $METRICS_PROJECT_ID
