@startuml external_navigation_sequence_diagram.puml

actor Bob

participant Router
participant RouteInformationProvider

box Parsing route information
participant MetricsRouteInformationParser
participant RouteConfigurationFactory
endbox

box Configuring pages
participant MetricsRouterDelegate
participant NavigationNotifier
participant MetricsPageFactory
endbox

Bob -> Router : Opens the Metrics URL
activate Router

Router -> RouteInformationProvider : Notifies about the URL changes
deactivate Router
activate RouteInformationProvider

RouteInformationProvider -> MetricsRouteInformationParser : parseRouteInformation(RouteInformation routeInformation)
deactivate RouteInformationProvider
activate MetricsRouteInformationParser

MetricsRouteInformationParser -> RouteConfigurationFactory : create(Uri uri)
activate RouteConfigurationFactory

return RouteConfiguration

alt Initial open page
    MetricsRouteInformationParser -> MetricsRouterDelegate : setInitialRoutePath(routeConfiguration)
    activate MetricsRouterDelegate

    MetricsRouterDelegate -> NavigationNotifier : setInitialRoutePath(routeConfiguration)
    activate NavigationNotifier
else Change the URL
    MetricsRouteInformationParser -> MetricsRouterDelegate : setNewRoutePath(routeConfiguration)

    MetricsRouterDelegate -> NavigationNotifier : setNewRoutePath(routeConfiguration)
end
deactivate MetricsRouteInformationParser

NavigationNotifier -> MetricsPageFactory : create(RouteConfiguration configuration)
activate MetricsPageFactory

return actual page

NavigationNotifier -> NavigationNotifier : add actual page to the page stack

NavigationNotifier --> MetricsRouterDelegate: notifyListeners()
deactivate NavigationNotifier

MetricsRouterDelegate -> MetricsRouterDelegate: applies new page stack

MetricsRouterDelegate --> Bob : shows the actual page
deactivate MetricsRouterDelegate

@enduml
