@startuml external_navigation_sequence_diagram.puml
skinparam ParticipantPadding 20
skinparam BoxPadding 10

actor Bob

participant Router
participant RouteInformationProvider

box Parsing Route Information
participant MetricsRouteInformationParser
participant RouteConfigurationFactory
endbox

box Managing Pages
participant MetricsRouterDelegate
participant NavigationNotifier
participant MetricsPageFactory
endbox

Bob -> Router : Opens the Metrics URL
activate Router

Router -> RouteInformationProvider : Notifies about the URL changes
deactivate Router
activate RouteInformationProvider

RouteInformationProvider -> Router : Route Information
deactivate RouteInformationProvider

Router -> MetricsRouteInformationParser : parseRouteInformation(routeInformation)
activate MetricsRouteInformationParser

MetricsRouteInformationParser -> RouteConfigurationFactory : create(uri)
activate RouteConfigurationFactory

return routeConfiguration

MetricsRouteInformationParser -> Router : routeConfiguration
deactivate MetricsRouteInformationParser

alt Initial page route
    Router -> MetricsRouterDelegate : setInitialRoutePath(routeConfiguration)
    activate MetricsRouterDelegate

    MetricsRouterDelegate -> NavigationNotifier : handleInitialRoutePath(routeConfiguration)
    activate NavigationNotifier
else Set new page route
    Router -> MetricsRouterDelegate : setNewRoutePath(routeConfiguration)

    MetricsRouterDelegate -> NavigationNotifier : handleNewRoutePath(routeConfiguration)
end


NavigationNotifier -> MetricsPageFactory : create(configuration)
activate MetricsPageFactory

return metricsPage

NavigationNotifier -> NavigationNotifier : add metricsPage to the pages

NavigationNotifier --> MetricsRouterDelegate: notifyListeners()
deactivate NavigationNotifier

MetricsRouterDelegate -> MetricsRouterDelegate: applies the updated pages

MetricsRouterDelegate --> Bob : shows a new metricsPage
deactivate MetricsRouterDelegate

@enduml
