@startuml external_navigation_sequence_diagram.puml
skinparam ParticipantPadding 20
skinparam BoxPadding 10

actor Bob

participant Router
participant RouteInformationProvider

box Parsing Route Information
participant MetricsRouteInformationParser
participant RouteConfigurationFactory
endbox

box Managing Pages
participant MetricsRouterDelegate
participant NavigationNotifier
participant MetricsPageFactory
endbox

Bob -> Router : Opens the Metrics URL
activate Router

Router -> RouteInformationProvider : Notifies about the URL changes
deactivate Router
activate RouteInformationProvider

RouteInformationProvider -> MetricsRouteInformationParser : parseRouteInformation(routeInformation)
deactivate RouteInformationProvider
activate MetricsRouteInformationParser

MetricsRouteInformationParser -> RouteConfigurationFactory : create(uri)
activate RouteConfigurationFactory

return routeConfiguration

alt Initial page route
    MetricsRouteInformationParser -> MetricsRouterDelegate : setInitialRoutePath(routeConfiguration)
    activate MetricsRouterDelegate

    MetricsRouterDelegate -> NavigationNotifier : setInitialRoutePath(routeConfiguration)
    activate NavigationNotifier
else Set new page route
    MetricsRouteInformationParser -> MetricsRouterDelegate : setNewRoutePath(routeConfiguration)

    MetricsRouterDelegate -> NavigationNotifier : setNewRoutePath(routeConfiguration)
end
deactivate MetricsRouteInformationParser

NavigationNotifier -> MetricsPageFactory : create(configuration)
activate MetricsPageFactory

return metricsPage

NavigationNotifier -> NavigationNotifier : add metricsPage to the pages

NavigationNotifier --> MetricsRouterDelegate: notifyListeners()
deactivate NavigationNotifier

MetricsRouterDelegate -> MetricsRouterDelegate: applies the updated pages

MetricsRouterDelegate --> Bob : shows a new metricsPage
deactivate MetricsRouterDelegate

@enduml
