@startuml internal_navigation_sequence_diagram
skinparam ParticipantPadding 20
skinparam BoxPadding 10

actor Bob



box Managing Pages
participant NavigationNotifier
participant MetricsPageFactory
participant MetricsRouterDelegate
endbox

participant Router

participant MetricsRouteInformationParser

Bob -> NavigationNotifier : pushNamed('newPage')
activate NavigationNotifier

NavigationNotifier -> MetricsPageFactory : create(configuration)
activate MetricsPageFactory

return updated metricsPage

NavigationNotifier -> NavigationNotifier : add metricsPage to the pages

NavigationNotifier -> MetricsRouterDelegate : notifyListeners()
deactivate NavigationNotifier
activate MetricsRouterDelegate

MetricsRouterDelegate -> MetricsRouterDelegate: applies the updated pages

MetricsRouterDelegate -> Router: notify
activate Router

Router -> MetricsRouteInformationParser : restoreRouteInformation(configuration)
activate MetricsRouteInformationParser

MetricsRouterDelegate --> Bob : shows a new metricsPage
deactivate MetricsRouterDelegate

MetricsRouteInformationParser -> Router : routeInformation
deactivate MetricsRouteInformationParser

Router -->  Bob : shows the updated URL
deactivate Router

@enduml
