@startuml internal_navigation_sequence_diagram
skinparam ParticipantPadding 20
skinparam BoxPadding 10

actor Bob



box Managing Pages
participant NavigationNotifier
participant MetricsPageFactory
participant MetricsRouterDelegate
endbox

participant MetricsRouteInformationParser

participant Router

Bob -> NavigationNotifier : pushNamed('newPage')
activate NavigationNotifier

NavigationNotifier -> MetricsPageFactory : create(configuration)
activate MetricsPageFactory

return updated metricsPage

NavigationNotifier -> NavigationNotifier : add metricsPage to the pages

NavigationNotifier -> MetricsRouterDelegate : notifyListeners()
deactivate NavigationNotifier
activate MetricsRouterDelegate

MetricsRouterDelegate -> MetricsRouterDelegate: applies the updated pages

MetricsRouterDelegate -> MetricsRouteInformationParser : restoreRouteInformation(configuration)
deactivate MetricsRouterDelegate
activate MetricsRouteInformationParser

MetricsRouteInformationParser -> Router : notifies about page changed
activate Router

Router --> Bob : shows the updated metricsPage
deactivate Router
@enduml
