@startuml internal_navigation_sequence_diagram

actor Bob

participant Router

box Configuring pages
participant NavigationNotifier
participant MetricsPageFactory
participant MetricsRouterDelegate
endbox

participant MetricsRouteInformationParser

participant RouteInformationProvider

Bob -> NavigationNotifier : pushNamed('new page')
activate NavigationNotifier

NavigationNotifier -> MetricsPageFactory : create(configuration)
activate MetricsPageFactory

return updated page

NavigationNotifier -> NavigationNotifier : add updated page to the page stack

NavigationNotifier -> MetricsRouterDelegate : notifyListeners()
deactivate NavigationNotifier
activate MetricsRouterDelegate

MetricsRouterDelegate -> MetricsRouterDelegate: applies new page stack

MetricsRouterDelegate -> MetricsRouteInformationParser : restoreRouteInformation(configuration)
MetricsRouterDelegate --> Bob : show new page
deactivate MetricsRouterDelegate
activate MetricsRouteInformationParser

MetricsRouteInformationParser -> RouteInformationProvider : routerReportsNewRouteInformation(routeInformation)
deactivate MetricsRouteInformationParser
activate RouteInformationProvider

RouteInformationProvider --> Router : notify about page changed
activate Router

Router --> Bob : show updated URL
deactivate Router
@enduml
