@startuml navigation_sequence_diagram

actor Bob

participant Router
participant RouteInformationProvider

box Parsing route information
participant MetricsRouteInformationParser
participant RouteConfigurationFactory
endbox

box Configuring pages
participant MetricsRouterDelegate
participant NavigationNotifier
participant MetricsPageFactory
endbox

Bob -> Router : Opens the Metrics URL
activate Router

Router -> RouteInformationProvider : Notifies about the URL changes
activate RouteInformationProvider

RouteInformationProvider -> MetricsRouteInformationParser : parseRouteInformation(RouteInformation routeInformation)
activate MetricsRouteInformationParser

MetricsRouteInformationParser -> RouteConfigurationFactory : create(Uri uri)
activate RouteConfigurationFactory

return RouteConfiguration

alt Initial open page
    MetricsRouteInformationParser -> MetricsRouterDelegate : setInitialRoutePath(routeConfiguration)
    activate MetricsRouterDelegate

    MetricsRouterDelegate -> NavigationNotifier : setInitialRoutePath(routeConfiguration)
    activate NavigationNotifier
else Change the URL
    MetricsRouteInformationParser -> MetricsRouterDelegate : setNewRoutePath(routeConfiguration)

    MetricsRouterDelegate -> NavigationNotifier : setNewRoutePath(routeConfiguration)
end

NavigationNotifier -> MetricsPageFactory : create(RouteConfiguration configuration)
activate MetricsPageFactory

MetricsPageFactory --> NavigationNotifier : actual page

NavigationNotifier --> NavigationNotifier : add actual page to the page stack

NavigationNotifier --> MetricsRouterDelegate: notifyListeners()

MetricsRouterDelegate --> MetricsRouterDelegate: applies new page stack

MetricsRouterDelegate --> Bob : shows the actual page

@enduml
