@startuml navigation_class_diagram

class MetricsApp {}

package common.presentation {

    package injector.widget {
        class InjectionContainer {}
    }

    package navigation {

        package route_configration {
            class RouteName {
            }

            class RouteConfiguration {
                + name : RouteName
                + path : String
                + authorizationRequired : bool
            }

            class RouteConfigurationFactory {
                + RouteConfiguration create(Uri)
            }
        }
        class MetricsRouteInformationParser {
            - RouteConfigurationFactory _routeConfigurationFactory
            + Future<RouteConfiguration> parseRouteInformation(RouteInformation)
            + RouteInformation restoreRouteInformation(RouteConfiguration)
        }
        class MetricsRouterDelegate {
            + navigatorKey : GlobalKey<NavigatorState>
            + currentConfiguration : RouteConfiguration
            + navigatorObservers : List<NavigatorObservers>
            - _navigationNotifier : NavigationNotifier
            + Future<void> setInitialRoutePath(RouteConfiguration routeConfiguration)
            + Future<void> setNewRoutePath(RouteConfiguration routeConfiguration)
        }

        package constants {
            class MetricsRoutes {}
        }

        package state {
            class NavigationNotifier {
                + pages : List<MetricsPage>
                + currentConfiguration : RouteConfiguration
                - _metricsPageFactory : MetricsPageFactory
                - _isUserLoggedIn : bool
                - _isAppInitialized : bool
                - _redirectRoute : RouteConfiguration
                + void handleAuthenticationUpdates(bool isLoggedIn)
                + void handleAppInitialized(bool isAppInitialized)
                + void pop()
                + void push(RouteConfiguration)
                + void pushReplacement(RouteConfiguration)
                + void pushAndRemoveUntil(RouteConfiguration, MetricsPredicate)
                + void handleInitialRoutePath(RouteConfiguration routeConfiguration)
                + void handleNewRoutePath(RouteConfiguration routeConfiguration)
                - void _redirect()
                - RouteConfiguration _processConfiguration(RouteConfiguration routeConfiguration)
            }
        }


        package metrics_page {
            class MetricsPageFactory {
                + MetricsPage create(RouteConfiguration)
            }

            class MetricsPage {
                + child : Widget
                + maintainState : bool
                + fullScreenDialog : bool
                + Route<T> createRoute()
            }

            class MetricsPageRoute {
                + builder : WidgetBuilder
                + settings : RouteSettings
                + maintainState : bool
                + fullscreenDialog : bool
                + Widget buildTransitions()
            }
        }

    }
}

InjectionContainer --> NavigationNotifier : provides

MetricsApp --> MetricsRouteInformationParser :uses
MetricsApp --> MetricsRouterDelegate : uses

MetricsRouteInformationParser --> RouteConfiguration : provides
MetricsRouteInformationParser --> RouteConfigurationFactory : uses

RouteConfiguration --> RouteName : uses

RouteConfigurationFactory -> RouteConfiguration : uses
RouteConfigurationFactory -> MetricsRoutes : uses

MetricsRouterDelegate --> NavigationNotifier : uses

NavigationNotifier --> RouteConfigurationFactory : uses
NavigationNotifier --> RouteConfiguration : uses
NavigationNotifier --> MetricsPageFactory : uses

MetricsPageFactory --> MetricsPage : uses

MetricsPage --> MetricsPageRoute : uses

@enduml
