@startuml
package auth.data.repositories {
    class FirebaseAnalyticsRepository {}
}

package auth.domain.repositories {
    abstract class AnalyticsRepository {
        Future<void> logPageView()
        Future<void> logLogin()
    }
}

FirebaseAnalyticsRepository ..|> AnalyticsRepository
@enduml
