source:
  jenkins:
    url: $CI_INTEGRATION_JENKINS_URL
    job_name: $ANCESTOR_JOB_NAME
    username: $JENKINS_USERNAME
    api_key: $JENKINS_API_KEY
destination:
  firestore:
    firebase_project_id: $FIREBASE_PROJECT_ID
    firebase_user_email: $WEB_APP_USER_EMAIL
    firebase_user_pass: $WEB_APP_USER_PASSWORD
    firebase_public_api_key: $CI_INTEGRATIONS_FIREBASE_API_KEY
    metrics_project_id: $METRICS_PROJECT_ID
