source:
  jenkins:
    url: http://ec2-54-218-41-22.us-west-2.compute.amazonaws.com:8080/
    job_name: Metrics Web
    username: $JENKINS_USERNAME
    api_key: $JENKINS_API_KEY
destination:
  firestore:
    firebase_project_id: metrics-d9c67
    firebase_user_email: $WEB_APP_USER_EMAIL
    firebase_user_pass: $WEB_APP_USER_PASSWORD
    firebase_public_api_key: $CI_INTEGRATIONS_FIREBASE_API_KEY
    metrics_project_id: metrics_web_jenkins_test
