@startuml public_dashboard_architecture_class

package feature_config.presentation {
    package models {
        class PublicDashboardFeatureConfigViewModel {}
    }

    package state {
        class FeatureConfigNotifier {}
    }
}

package auth {
    package domain {
        package usecases {
            class SignInAnonymouslyUseCase {}
        }

        package repositories {
            interface UserRepository {}
        }
    }

    package presentation as auth.presentation {
        package models as auth.presentation.models {
            enum AuthState {}
        }


        package state as auth.presentation.state {
            class AuthNotifier {}
        }

        package view_models as auth.presentation.view_models {
            class UserProfileViewModel {}
        }
    }
}

package common.presentation {
    package widgets as common.presentation.widgets {
        class MetricsUserMenu {}
    }

    package navigation.state {
        class NavigationNotifier {}
    }
}


FeatureConfigNotifier --> PublicDashboardFeatureConfigViewModel : provides

AuthNotifier -left-> UserProfileViewModel : provides
AuthNotifier --> SignInAnonymouslyUseCase : uses
AuthNotifier -right-> AuthState : uses

SignInAnonymouslyUseCase --> UserRepository : uses

MetricsUserMenu --> UserProfileViewModel : uses
NavigationNotifier --> AuthState : uses

@enduml
