@startuml codeecov_sequence_diagram


actor Bob


participant CodeCovConverterRunner
participant CodeCovArgumentsParser
participant SpecificCovConverterCommand
participant SpecificCovConverter


Bob -> CodeCovConverterRunner : codecov_converter specific -i input.json -o output.json

activate CodeCovConverterRunner
CodeCovConverterRunner -> CodeCovArgumentsParser : parse(arguments)
activate CodeCovArgumentsParser
return CodeCovArguments instance
CodeCovConverterRunner -> SpecificCovConverterCommand : run()
activate SpecificCovConverterCommand
SpecificCovConverterCommand -> SpecificCovConverter : convert(inputFile)
activate SpecificCovConverter
return CoverageModel instance
SpecificCovConverterCommand -> SpecificCovConverterCommand : write Coverage as a json to output file
return 
return

@enduml