include: package:lint/analysis_options.yaml

# https://github.com/passsy/dart-lint
linter:
  rules:
    - unawaited_futures # https://dart-lang.github.io/linter/lints/unawaited_futures.html
    - public_member_api_docs # https://dart-lang.github.io/linter/lints/public_member_api_docs.html

# https://github.com/passsy/dart-lint/blob/master/lib/analysis_options.yaml
analyzer:
  errors:
    avoid_print: ignore
    avoid_classes_with_only_static_members: ignore
    unawaited_futures: error
