@startuml metrics_concept_map

skinparam DefaultTextAlignment left

skinparam database {
    borderColor #292618
    backgroundColor #fed100
}

skinparam cloud {
    borderColor #002366
    backgroundColor #007FFF
    fontColor white
}

skinparam rectangle {
    borderColor #182b27
    backgroundColor #20ce9a
    roundCorner 10
}

skinparam ArrowColor #4f4f56

cloud Jenkins
cloud "GitHub Actions" as GA
cloud Buildkite

rectangle "CI integrations" as CI
rectangle "Dart Cloud Functions" as DartCloudFunctions

together {
    node Firebase {
        cloud Hosting
        database Firestore
        cloud Authentication
        cloud "Cloud Functions" as CloudFunctions
        cloud Analytics
    }

    rectangle Core
}
rectangle Web
rectangle "CLI"

cloud Sentry

Jenkins -[hidden]right-> GA
GA -[hidden]right-> Buildkite

Core -[hidden]left-> Analytics  

Jenkins -down-> CI : data
GA -down-> CI : data
Buildkite -down-> CI : data

CI -down-> Firestore : sync data
CI -down-> Authentication : authenticates
CI -[hidden]down-> Hosting

Hosting -[hidden]right-> Authentication
Authentication -[hidden]right-> Firestore

Web --up--> Firestore : reads metrics and \l stores app config
Web --up--> Authentication : authenticates
Web --up--> Hosting : deployed on
Web --up--> Analytics : reports analytics data
Web -down-> Sentry : reports about errors

DartCloudFunctions -up-> CloudFunctions : deployed on
DartCloudFunctions -[hidden]-> Core : uses
DartCloudFunctions -up-> Firestore : creates aggregation \l documents

CLI --> Web : deploys
CLI --> Core : uses

DartCloudFunctions -down-> Core : uses
Web --right--> Core : uses
CI --right--> Core  : uses

@enduml
