name: yaml_map
description: Dart package to parse and format the yaml files.
version: 1.0.0

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  yaml: ^2.2.0

dev_dependencies:
  lint: ^1.1.1
  test: ^1.6.0
