@startuml debug_menu_update_config_sequence_diagram.puml

skinparam ParticipantPadding 20
skinparam BoxPadding 10

actor Bob

box "presentation"
    participant UI
    participant DebugMenuNotifier << (C,#ADD1B2) >>
end box

box "domain"
    participant UpdateLocalConfigUseCase << (C,#ADD1B2) >>
end box

box "data"
    participant HiveLocalConfigRepository << (C,#ADD1B2) >>
end box

database "IndexedDB" as DB

Bob -> UI : Toggles FPS Monitor

UI -> DebugMenuNotifier : toggleFpsMonitor()
activate DebugMenuNotifier

DebugMenuNotifier -> UpdateLocalConfigUseCase : call(localConfigParam)
activate UpdateLocalConfigUseCase

UpdateLocalConfigUseCase -> HiveLocalConfigRepository : updateConfig(//expose localConfigParam//)
activate HiveLocalConfigRepository

HiveLocalConfigRepository -> DB : Update 'local_config' box

return newLocalConfig
return newLocalConfig
return "Notify about config updates"

UI --> Bob : UI changes

@enduml
