@startuml debug_menu_data_layer_class_diagram

package debug_menu {
        package data {
            package repositories {
                class HiveLocalConfigRepository {}
            }

            package model {
                class LocalConfigData {
                    + factory fromJson(Map<String, dynamic> json)
                    + Map<String, dynamic> toJson()
                }
            }
        }

        package domain.repositories {
            interface LocalConfigRepository {}
        }

        package domain.entities {
            class LocalConfig {}
        }

}

package core.data.model {
    abstract class DataModel {
        + Map<String, dynamic> toJson()
    }
}

HiveLocalConfigRepository --> LocalConfigData : uses
HiveLocalConfigRepository ..|> LocalConfigRepository

LocalConfigData ..|> DataModel
LocalConfigData --|> LocalConfig

@enduml
