@startuml converter_exception_class_diagram


package common.exception {
    class CoverageConverterException{
        code: CoverageConverterErrorCode
        stackTrace: StackTrace
        {method} String message
        String toString()
    }


    package error_code {
        enum CoverageConverterErrorCode {
            noSuchFile
            fileIsEmpty
            invalidFileFormat
        }
    }

}


CoverageConverterException -> CoverageConverterErrorCode : uses

@enduml
