@startuml coverage_conversion_activity 

(*) --> Coverage
---> "Get the input file path from the arguments"
if "Input file exists" then
---> [true] "Parse the input file to the specific coverage report instance"
if "Parsing succeessfull" then
---> [true] "Convert the input file to the CoverageData instance"
---> "Create a coverage json from the CoverageData instance"
---> "Create an output coverage file"
---> "Write a coverage json to the coverage file"
--> (*)

else 
---> ===EXCEPTION===
--> [false] "Throw a CoverageConverterException"
--> (*)
endif

else 
---> ===EXCEPTION===
endif

@enduml
