@startuml coverage_sequence_diagram


actor Bob


participant CoverageConverterRunner
participant CoverageArgumentsParser
participant SpecificCoverageConverterCommand
participant SpecificCoverageConverter


Bob -> CoverageConverterRunner : codecov_converter specific -i input.json -o output.json

activate CoverageConverterRunner
CoverageConverterRunner -> CoverageArgumentsParser : parse(arguments)
activate CoverageArgumentsParser
return CoverageArguments instance
CoverageConverterRunner -> SpecificCoverageConverterCommand : run()
activate SpecificCoverageConverterCommand
SpecificCoverageConverterCommand -> SpecificCoverageConverter : convert(inputFile)
activate SpecificCoverageConverter
return CoverageModel instance
SpecificCoverageConverterCommand -> SpecificCoverageConverterCommand : write Coverage as a json to output file
return 
return

@enduml