@startuml coverage_sequence_diagram

actor Bob

participant CoverageConverterRunner
participant SpecificCoverageConverterCommand
participant CoverageConverterArgumentsManager
participant SpecificCoverageConverter

Bob -> CoverageConverterRunner : coverage_converter specific -i input.json -o output.json

activate CoverageConverterRunner
CoverageConverterRunner -> SpecificCoverageConverterCommand : run()
activate SpecificCoverageConverterCommand

SpecificCoverageConverterCommand -> CoverageConverterArgumentsManager : parseArgResults(argResults)
activate CoverageConverterArgumentsManager


alt inputFile == null
    activate CoverageConverterArgumentsManager

    return throw ArgumentError
    activate SpecificCoverageConverterCommand
    ' return throw ArgumentError
    SpecificCoverageConverterCommand -> CoverageConverterRunner: throw ArgumentError
    deactivate SpecificCoverageConverterCommand
    activate CoverageConverterRunner
    CoverageConverterRunner -> Bob: prints error message
    deactivate CoverageConverterRunner

end

return CoverageArguments instance


alt !inputFile.exists
    activate SpecificCoverageConverterCommand

    SpecificCoverageConverterCommand --> CoverageConverterRunner: throw an CoverageConverterException
    deactivate SpecificCoverageConverterCommand

    activate CoverageConverterRunner

    CoverageConverterRunner -> Bob : prints error message
    deactivate CoverageConverterRunner

end

SpecificCoverageConverterCommand -> SpecificCoverageConverter : convert(inputFile)
activate SpecificCoverageConverter
return CoverageData instance
SpecificCoverageConverterCommand -> SpecificCoverageConverterCommand : write Coverage as a json to output file
return
return

@enduml
