@startuml coverage_interfaces_diagram.puml

package package:args {
    class Command {
        name: String
        description: String
        FutureOr<T> run()
    }
}


package core.src.data.model {
    class CoverageData {
        Percent percent
        Map<String, dynamic> toJson()
        factory fromJson
    }
}


package common {
    package arguments {
        package model {
            class CoverageConverterArguments {
                inputFilePath : String
                outputFilePath : String
            }
        }

        package parser {
            abstract ArgumentsParser<T extends CoverageConverterArguments> {
                void configureArguments(ArgParser)
                {abstract} T parseArgResults(ArgResults)
            }
        }
    }


    package command {
        abstract CoverageConverterCommand<T exetends CoverageConverterArguments> {
            argumentsParser: ArgumentsParser<T>
            {abstract} converter : CoverageConverter<T, R>
            {abstract} name: String
            {abstract} description: String
            void run()
        }
    }

    package converter {
        interface CoverageConverter<T extends CoverageConverterArguments, R> {
            {abstract} CoverageData convert(R, T)
            {abstract} R parse(File)
        }
    }
}

CoverageConverterCommand --|> Command
CoverageConverter --> CoverageData : provides
CoverageConverterCommand --> CoverageConverter : uses
CoverageConverterCommand --> ArgumentsParser : uses
ArgumentsParser --> CoverageConverterArguments : provides

@enduml
