@startuml coverage_class_diagram

package arguments {
    package model {
        class CoverageConverterArguments {
            inputFilePath : String
            outputFilePath : String
        }
    }

    package manager {
        class CoverageConverterArgumentsManager {
            void configureArguments(ArgParser)
            CoverageConverterArguments parseArgResults(ArgResults)
        }
    }
}

package common {
    package command {
        abstract CoverageConverterCommand {
            arguments : CoverageConverterArguments
            {abstract} converter : CoverageConverter
            {abstract} name: String
            {abstract} description: String
            void run()
        }
    }

    package converter {
        interface CoverageConverter {
            {abstract} CoverageData convert(File)
        }
    }


    package runner {
        class CoverageConverterRunner {
            argParser : CoverageConverterArgumentsParser
        }
    }

    package exceptions {
        class CoverageConverterException{
            code: CoverageConverterErrorCode
            {method} String message
            String toString()
        }


        package error_code {
            enum CoverageConverterErrorCode {
                noSuchFile
                fileIsEmpty
                invalidFileFormat
            }
        }
    }
}

package specific_format {
    package converter as specific_format.converter {
        class SpecificFormatCoverageConverter {
            CoverageData convert(File)
        }
    }

    package command as specific_format.command {
        class SpecificFormatCoverageConverterCommand {
            converter : SpecificFormatCoverageConverter
            name: String
            description: String
        }
    }
}


CoverageConverterRunner -right-> SpecificFormatCoverageConverterCommand : uses

CoverageConverterArgumentsManager -left-> CoverageConverterArguments : provides

SpecificFormatCoverageConverterCommand --> SpecificFormatCoverageConverter : uses
SpecificFormatCoverageConverterCommand --|> CoverageConverterCommand

SpecificFormatCoverageConverter .down.|> CoverageConverter

CoverageConverterCommand --> CoverageConverterArguments : uses
CoverageConverterCommand -left-> CoverageConverter : uses
CoverageConverterCommand -up-> CoverageConverterException : throws
CoverageConverterCommand --> CoverageConverterArgumentsManager : uses

CoverageConverterException --> CoverageConverterErrorCode : uses



@enduml
