@startuml database_finished_updating

participant Bob

participant MetadataNotifier

participant ReceiveStorageMetadataUpdates

participant FirestoreStorageMetadataRepository

participant NavigationNotifier

participant BrowserNavigationState

database Firestore



Bob -> MetadataNotifier : opens the app
activate MetadataNotifier
MetadataNotifier -> ReceiveStorageMetadataUpdates : get database metadata updates
activate ReceiveStorageMetadataUpdates
ReceiveStorageMetadataUpdates -> FirestoreStorageMetadataRepository : get database metadata updates
activate FirestoreStorageMetadataRepository
FirestoreStorageMetadataRepository --> Firestore : get database metadata updates
activate Firestore
Firestore --> FirestoreStorageMetadataRepository : return database metadata updates
deactivate Firestore
FirestoreStorageMetadataRepository --> ReceiveStorageMetadataUpdates : return database metadata updates
deactivate FirestoreStorageMetadataRepository
ReceiveStorageMetadataUpdates --> MetadataNotifier : return database metadata updates
deactivate ReceiveStorageMetadataUpdates

MetadataNotifier -> MetadataNotifier : subscribes to database metadata updates
MetadataNotifier -> MetadataNotifier : receives database metadata snapshot

alt database is updating

    MetadataNotifier -> NavigationNotifier : notifies database updating
    activate NavigationNotifier
    NavigationNotifier --> Bob : shows application updating page
    deactivate NavigationNotifier

else

    MetadataNotifier -> NavigationNotifier : notifies database is not updating
    activate NavigationNotifier

    alt currentPage == ApplicationUpdatingPage

        NavigationNotifier -> BrowserNavigationState : refresh
        activate BrowserNavigationState
        BrowserNavigationState --> Bob : refreshes the browser page
        deactivate BrowserNavigationState
        deactivate NavigationNotifier

    end

end

deactivate MetadataNotifier


@enduml
