@startuml metadata_domain_class_diagram

package base.domain.usecases {
    interface UseCase<Type, Params> {
        + call(Params) : Type
    }
}

package metadata.domain {
    package entities {
        class DatabaseMetadata {
            + version : String
            + isUpdating : bool
        }
    }

    package repositories {
        interface DatabaseMetadataRepository {
            + databaseMetadataStream() : Stream<DatabaseMetadata>
        }
    }

    package usecases {
        class ReceiveDatabaseMetadataUpdates implements UseCase{
            - databaseMetadataRepository : DatabaseMetadataRepository
            + call() : Stream<DatabaseMetadata>
        }
    }

}

ReceiveDatabaseMetadataUpdates --> DatabaseMetadataRepository : provides
DatabaseMetadataRepository --> DatabaseMetadata : provides
ReceiveDatabaseMetadataUpdates --> DatabaseMetadata : uses



@enduml
