@startuml metadata_sequence_diagram


participant Bob

participant MetadataNotifier

participant ReceiveDatabaseMetadataUpdates

participant ApplicationMetadata

participant FirestoreDatabaseMetadataRepository

participant NavigationNotifier

participant AuthNotifier


database Firestore


Bob -> MetadataNotifier : opens the application
activate MetadataNotifier

MetadataNotifier -> ReceiveDatabaseMetadataUpdates : get database metadata updates stream
activate ReceiveDatabaseMetadataUpdates
ReceiveDatabaseMetadataUpdates -> FirestoreDatabaseMetadataRepository : get database metadata stream
activate FirestoreDatabaseMetadataRepository
FirestoreDatabaseMetadataRepository -> Firestore : get database metadata stream
activate Firestore
Firestore --> FirestoreDatabaseMetadataRepository : returns database metadata stream
deactivate Firestore
FirestoreDatabaseMetadataRepository --> ReceiveDatabaseMetadataUpdates : return database metadata updates stream
deactivate FirestoreDatabaseMetadataRepository
ReceiveDatabaseMetadataUpdates --> MetadataNotifier : return database metadata updates stream
deactivate ReceiveDatabaseMetadataUpdates

MetadataNotifier -> MetadataNotifier : listen to database metadata updates stream

loop receives new database metadata

    alt database is updating

        MetadataNotifier -> NavigationNotifier : notifies database updating
        activate NavigationNotifier
        NavigationNotifier --> Bob : redirects to the ApplicationUpdatingPage
        deactivate NavigationNotifier
        MetadataNotifier -> AuthNotifier : log out user
        activate AuthNotifier
        AuthNotifier --> Bob : logs out
        deactivate AuthNotifier


    end

    MetadataNotifier -> ApplicationMetadata : get application version
    activate ApplicationMetadata

    ApplicationMetadata --> MetadataNotifier : application version
    deactivate ApplicationMetadata


    alt databaseVersion != applicationVersion

        MetadataNotifier -> NavigationNotifier : notifies database version not compatible
        activate NavigationNotifier
        NavigationNotifier --> Bob : redirects to the ApplicationIsOutdatedPage
        deactivate NavigationNotifier
        MetadataNotifier -> AuthNotifier : log out user
        activate AuthNotifier
        AuthNotifier --> Bob : logs out
        deactivate AuthNotifier


    end

end


@enduml
