@startuml metadata_data_class_diagram

package core.data.model {
    class DataModel {
        + toJson() : Map<String, dynamic>
    }
}

package metadata {

    package domain {
        package entities {
            class StorageMetadata {
                + version : String
                + isUpdating : bool
            }
        }

        package repositories as domain.repositories {
            interface StorageMetadataRepository {
                + storageMetadataStream() : Stream<StorageMetadata>
            }
        }

    }

    package data {
        package model {
            class StorageMetadataData extends StorageMetadata implements DataModel {
                + {static} fromJson() : StorageMetadataData
            }
        }


        package repositories {
            class FirestoreStorageMetadataRepository implements StorageMetadataRepository {
                - firestore : Firestore
            }
        }
    }
}

FirestoreStorageMetadataRepository --> StorageMetadataData : provides

StorageMetadataRepository -> StorageMetadata : provides


@enduml
