@startuml metadata_domain_class_diagram

package base.domain.usecases {
    interface UseCase<Type, Params> {
        + call(Params) : Type
    }
}

package metadata.domain {
    package entities {
        class StorageMetadata {
            + version : String
            + isUpdating : bool
        }
    }

    package repositories {
        interface StorageMetadataRepository {
            + storageMetadataStream() : Stream<StorageMetadata>
        }
    }

    package usecases {
        class ReceiveStorageMetadataUpdates implements UseCase {
            - storageMetadataRepository : StorageMetadataRepository
            + call() : Stream<StorageMetadata>
        }
    }

}

ReceiveStorageMetadataUpdates --> StorageMetadataRepository : provides
StorageMetadataRepository --> StorageMetadata : provides
ReceiveStorageMetadataUpdates --> StorageMetadata : uses



@enduml
