@startuml

package base.domain.usecases {
    class GetRemoteConfigUseCase{}
}

package common.presentation.state {
    class RemoteConfigNotifier {
        + isLoginFormEnabled : bool
        + isFpsMonitorEnabled : bool
        + isRendererDisplayEnabled : bool
        + isLoading : bool

        - _remoteConfig : RemoteConfig
        - _getRemoteConfigUseCase : GetRemoteConfigUseCase
        - Future<void> _initializeRemoteConfig()
    }
}

package widgets {}

RemoteConfigNotifier --> widgets : notifies
widgets --> RemoteConfigNotifier : notifies

RemoteConfigNotifier --> GetRemoteConfigUseCase : uses

@enduml
