@startuml remote_config_data_layer_class_diagram

package common.domain.repository {
    interface RemoteConfigurationRepository {}
}

package common.domain.entities {
    interface RemoteConfiguration {}
}

package common.data {
    package repository {
        class FirebaseRemoteConfigurationRepository {}
    }

    package deserializer {
        class RemoteConfigurationDeserializer {
            # RemoteConfiguration fromMap(Map<String, RemoteConfigValue> map)
        }
    }
}

FirebaseRemoteConfigurationRepository ..|> RemoteConfigurationRepository
FirebaseRemoteConfigurationRepository --> RemoteConfigurationDeserializer : uses

RemoteConfigurationDeserializer --> RemoteConfiguration : uses

@enduml
