@startuml web_layers_sequence_diagram
    skinparam ParticipantPadding 20
    skinparam BoxPadding 10

    actor Bob

    box "presentation"
        participant RemoteConfigNotifier << (C,#ADD1B2) >>
    end box

    box "domain"
        participant GetRemoteConfigUseCase << (C,#ADD1B2) >>
    end box

    box "data"
        participant RemoteConfigRepository << (C,#ADD1B2) >>
        participant FirebaseRemoteConfigAdapter << (C,#ADD1B2) >>
    end box

    database "Persistent Store" as PS

    Bob -> RemoteConfigNotifier : Enters the application
    activate RemoteConfigNotifier

    RemoteConfigNotifier -> GetRemoteConfigUseCase : call()
    activate GetRemoteConfigUseCase

    GetRemoteConfigUseCase -> RemoteConfigRepository : getConfig()
    activate RemoteConfigRepository

    RemoteConfigRepository -> PS : Get remote config

    PS -> RemoteConfigRepository : Remote config

    RemoteConfigRepository -> FirebaseRemoteConfigAdapter : FirebaseRemoteConfigAdapter(remoteConfig)
    activate FirebaseRemoteConfigAdapter

    return remoteConfig
    return remoteConfig
    return remoteConfig


    return Application shows or hides UI parts



    deactivate RemoteConfigRepository

@enduml
