@startuml remote_config_sequence_diagram
skinparam ParticipantPadding 20
skinparam BoxPadding 10

actor Bob

box "presentation"
participant UI
participant RemoteConfigurationNotifier << (C,#ADD1B2) >>
end box

box "domain"
participant SetDefaultRemoteConfigurationUseCase << (C,#ADD1B2) >>
participant FetchRemoteConfigurationUseCase << (C,#ADD1B2) >>
end box

box "data"
participant FirebaseRemoteConfigurationRepository << (C,#ADD1B2) >>
participant RemoteConfigurationDeserializer << (C,#ADD1B2) >>
end box

database "Firebase Remote Config" as FRC

Bob -> UI : Enters the application
activate UI

UI -> RemoteConfigurationNotifier : Initialize remote configuration
activate RemoteConfigurationNotifier

RemoteConfigurationNotifier -> SetDefaultRemoteConfigurationUseCase : call(remoteConfigurationParams)
activate SetDefaultRemoteConfigurationUseCase

SetDefaultRemoteConfigurationUseCase -> FirebaseRemoteConfigurationRepository : setDefaults(isLoginFormEnabled, isFpsMonitorEnabled, isRendererDisplayEnabled)
activate FirebaseRemoteConfigurationRepository
deactivate SetDefaultRemoteConfigurationUseCase

RemoteConfigurationNotifier -> FetchRemoteConfigurationUseCase : call()
activate FetchRemoteConfigurationUseCase

FetchRemoteConfigurationUseCase -> FirebaseRemoteConfigurationRepository : fetch()

FirebaseRemoteConfigurationRepository -> FRC : Fetch remote configuration

FRC --> FirebaseRemoteConfigurationRepository : Remote config

FetchRemoteConfigurationUseCase -> FirebaseRemoteConfigurationRepository : activate()
FetchRemoteConfigurationUseCase -> FirebaseRemoteConfigurationRepository : getConfiguration()

FirebaseRemoteConfigurationRepository -> RemoteConfigurationDeserializer : .fromMap(remoteConfigMap)
activate RemoteConfigurationDeserializer

RemoteConfigurationDeserializer --> FirebaseRemoteConfigurationRepository : remoteConfig
deactivate RemoteConfigurationDeserializer

FirebaseRemoteConfigurationRepository --> FetchRemoteConfigurationUseCase : remoteConfig
deactivate FirebaseRemoteConfigurationRepository

FetchRemoteConfigurationUseCase --> RemoteConfigurationNotifier : remoteConfig
deactivate FetchRemoteConfigurationUseCase

RemoteConfigurationNotifier --> UI : Notify about new configurations
deactivate RemoteConfigurationNotifier

UI --> Bob : Dismiss the loading screen
deactivate UI

@enduml
