@startuml

package common.domain.repository {
    interface RemoteConfigRepository {}
}

package common.domain.entities {
    interface RemoteConfig {}
}

package common.data {
    package repository {
        class FirebaseRemoteConfigRepository {}
    }

    package adapter {
        class FirebaseRemoteConfigAdapter {}
    }
}

FirebaseRemoteConfigRepository ..|> RemoteConfigRepository
FirebaseRemoteConfigRepository --> FirebaseRemoteConfigAdapter : uses

FirebaseRemoteConfigAdapter ..|> RemoteConfig

@enduml
