# A template for ci_integrations config with the Github Actions integration as a `source`.
# Consider the following links to familiarize yourself with Github Actions:
# - https://docs.github.com/en/free-pro-team@latest/rest/reference/actions
# - https://docs.github.com/en/free-pro-team@latest/actions/reference/authentication-in-a-workflow

source:
  # The `github_actions` key defines that the following source config stands for Github Actions integration.
  github_actions:

    # A unique identifier of the Github Actions workflow to integrate.
    #
    # This identifier is used to determine a workflow from where we will get new builds.
    #
    # You can get it from your Github link. For example: `https://github.com/{repository_owner}/{repository_name}/actions/runs/{workflow_id}`
    workflow_identifier: ...

    # A name of the project's repository.
    #
    # The name is used to associate a repository with the workflows.
    repository_name: ...

    # An owner of the project's repository.
    #
    # The field is used to associate an owner with the repository described above.
    repository_owner: ...

    # A Github access token using to authenticate you.
    #
    # Here is a guide how to create one - https://docs.github.com/en/enterprise/2.17/user/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line
    access_token: ...

destination:
# Add your destination config here.
