source:
  jenkins:
    url: sample_url
    job_name: test_project
    username: username
    api_key: key
destination:
  firestore:
    firebase_project_id: firebaseId
    firebase_user_email: user_email
    firebase_user_pass: user_pass
    firebase_web_api_key: firebase_web_api_key
    metrics_project_id: id
