source:
  jenkins:
    url: sample_url
    username: username
    password: password
    job_name: test_project
destination:
  firestore:
    firebase_project_id: firebaseId
    metrics_project_id: id
