@startuml database_finished_updating

participant Bob

participant MetadataNotifier

participant ReceiveDatabaseMetadataUpdates

participant FirestoreDatabaseMetadataRepository

participant NavigationNotifier

participant BrowserNavigationState

database Firestore



Bob -> MetadataNotifier : opens the app
activate MetadataNotifier
MetadataNotifier -> ReceiveDatabaseMetadataUpdates : get database metadata updates
activate ReceiveDatabaseMetadataUpdates
ReceiveDatabaseMetadataUpdates -> FirestoreDatabaseMetadataRepository : get database metadata updates
activate FirestoreDatabaseMetadataRepository
FirestoreDatabaseMetadataRepository --> Firestore : get database metadata updates
activate Firestore
Firestore --> FirestoreDatabaseMetadataRepository : return database metadata updates
deactivate Firestore
FirestoreDatabaseMetadataRepository --> ReceiveDatabaseMetadataUpdates : return database metadata updates
deactivate FirestoreDatabaseMetadataRepository
ReceiveDatabaseMetadataUpdates --> MetadataNotifier : return database metadata updates
deactivate ReceiveDatabaseMetadataUpdates

MetadataNotifier -> MetadataNotifier : subscribes to database metadata updates
MetadataNotifier -> MetadataNotifier : receives database metadata snapshot

alt database is updating

    MetadataNotifier -> NavigationNotifier : notifies database updating
    activate NavigationNotifier
    NavigationNotifier --> Bob : shows application updating page
    deactivate NavigationNotifier

else

    MetadataNotifier -> NavigationNotifier : notifies database is not updating
    activate NavigationNotifier

    alt currentPage == ApplicationUpdatingPage

        NavigationNotifier -> BrowserNavigationState : refresh
        activate BrowserNavigationState
        BrowserNavigationState --> Bob : refreshes the browser page
        deactivate BrowserNavigationState
        deactivate NavigationNotifier

    end

end

deactivate MetadataNotifier


@enduml