@startuml metadata_data_class_diagram

package core.data.model {
    class DataModel {
        + toJson() : Map<String, dynamic>
    }
}

package metadata {

    package domain {
        package entities {
            class DatabaseMetadata {
                + version : String
                + isUpdating : bool
            }
        }

        package repositories as domain.repositories {
            class DatabaseMetadataRepository {
                + databaseMetadataStream() : Stream<DatabaseMetadata>
            }
        }

    }

    package data {
        package model {
            class DatabaseMetadataData extends DatabaseMetadata implements DataModel {
                + {static} fromJson() : DatabaseMetadataData
            }
        }


        package repositories {
            class FirestoreDatabaseMetadataRepository implements DatabaseMetadataRepository {
                - firestore : Firestore
            }
        }
    }
}

FirestoreDatabaseMetadataRepository --> DatabaseMetadataData : provides



@enduml
