@startuml custom_approach_component_diagram

skinparam componentStyle rectangle

component Browser #A9DCDF

package "Metrics Web" {
    component NavigationComponent
    component ApplicationState
    component "User Interface" as UI
}

Browser -down-> NavigationComponent : notifies about \n URL updates
NavigationComponent -down-> ApplicationState : opens new pages, \n provides deep links
ApplicationState -down-> UI : data to display

UI -up-> ApplicationState : UI events(sorting, filtering, etc.)
ApplicationState -up-> NavigationComponent : deep links updates
NavigationComponent -up-> Browser : updates URL

@enduml
