@startuml custom_approach_component_diagram

skinparam componentStyle rectangle

component Browser #A9DCDF

package "Metrics Web" {
    component "Navigator 2.0" as Navigator
    component ApplicationState
    component "User Interface" as UI
}

Browser -down-> Navigator: notifies about \n URL updates
Navigator -down-> ApplicationState: opens new pages, \n provides deep links
ApplicationState -down-> UI: data to display

UI -up-> ApplicationState: UI events(sorting, filtering, etc.)
ApplicationState -up-> Navigator: deep links updates
Navigator -up-> Browser: updates URL

@enduml
