@startuml custom_approach_component_diagram

skinparam componentStyle rectangle

component Browser #A9DCDF
component NavigationComponent
component ApplicationState

Browser --> NavigationComponent : notifies about \n URL updates
NavigationComponent --> Browser : requests to \n update URLs
ApplicationState --> NavigationComponent : notifies about \nnavigation state changes
NavigationComponent --> ApplicationState : updates application \n navigation state
@enduml
