@startuml deep_links_integration_component_diagram

skinparam componentStyle rectangle

legend top left
| Color | Arrow type |
|<#B70033>| Existing relationship |
|<#Green>| New relationship |
endlegend

component "Browser History" as History #A9DCDF
component Browser #A9DCDF

package "Metrics Web" {
    component RouteInformationProvider
    component RouteInformationParser
    component RouterDelegate
    component NavigationState
    component NavigationNotifier
    component ApplicationState
}

History -right-> Browser: provides URLs

Browser -down-> RouteInformationProvider: URL

RouteInformationProvider -down-> RouteInformationParser: routeInformation

RouteInformationParser -down-> RouterDelegate: routeConfiguration

RouterDelegate -down-> NavigationNotifier: delegate handling\n new routeConfiguration

NavigationNotifier -right-> NavigationState: updates

NavigationNotifier -[#Green]up-> ApplicationState: updates

ApplicationState -[#Green]up-> NavigationNotifier: UI events \n (e.g. filtering, searching, \n back button pressed)

NavigationNotifier -[#Green]up-> History: updates URL query parameters

@enduml
