@startuml

abstract class PageNotifier {
    + pageParametersUpdatesStream : Stream<PageParameters>

    + handlePageParameters(PageParameters parameters) : void
}

class PageParametersDispatcher {
    + pageNotifiers : List<PageNotifier>
    + child : Widget
}

class MetricsPage<T> {}

class MetricsPageFactory {}

class RouteConfiguration {
    + name : RouteName
    + path : String
    + authorizationRequired : bool
    + queryParameters : Map<String, dynamic>

    + toLocation() : String
}

class RouteConfigurationFactory {}

abstract class PageParameters {
    + toQueryParameters() : Map<String, dynamic>
}

class DashboardPageParameters {
    + selectedProjectGroup : String
}

class NavigationNotifier {}

package common {
    package presentation {
        package state {
            class ProjectMetricsNotifier {
            }
        }
    }
}

PageParametersDispatcher --> PageNotifier : uses

PageNotifier --|> ChangeNotifier
PageNotifier --> PageParameters : uses

ProjectMetricsNotifier --|> PageNotifier

MetricsPageFactory --> MetricsPage : creates

RouteConfigurationFactory --> RouteConfiguration : creates

DashboardPageParameters ..|> PageParameters

@enduml