@startuml parsing_deep_links_class_diagram

package common.presentation.navigation {
    class MetricsRouteInformationParser {
        - _routeConfigurationFactory : RouteConfigurationFactory

        + parseRouteInformation(information: RouteInformation) : RouteConfiguration
        + restoreRouteInformation(configuration: RouteConfiguration) : RouteInformation
    }

    package route_configuration {
        class RouteConfiguration {
            + name : RouteName
            + path : String
            + authorizationRequired : bool
            + parameters : Map<String, dynamic>

            - RouteConfiguration._(name: RouteName, path: String, authorizationRequired: bool, parameters: Map<String, dynamic> parameters) : RouteConfiguration
            + RouteConfiguration.dashboard(parameters: Map<String, dynamic>): RouteConfiguration
            + RouteConfiguration.projectGroups(parameters: Map<String, dynamic>): RouteConfiguration
            + RouteConfiguration.login(parameters: Map<String, dynamic>): RouteConfiguration
            + RouteConfiguration.debugMenu(parameters: Map<String, dynamic>): RouteConfiguration
            + RouteConfiguration.loading(parameters: Map<String, dynamic>): RouteConfiguration

            + copyWith(name: RouteName, path: String, authorizationRequired: bool, parameters: Map<String, dynamic> parameters) : RouteConfiguration
            + getUrl() : String
        }

        class RouteConfigurationFactory {
            + create(uri: Uri) : RouteConfiguration
        }
    }
}

package flutter.material {
    class RouteInformation {
        + location: String
        + state: Object
    }
}

MetricsRouteInformationParser --> RouteConfiguration : uses
MetricsRouteInformationParser -up-> RouteInformation : uses
MetricsRouteInformationParser --> RouteConfigurationFactory : uses

RouteConfigurationFactory --> RouteConfiguration : creates

@enduml
