@startuml updating_deep_links_sequence_diagram

skinparam ParticipantPadding 20
skinparam BoxPadding 10

actor Bob

participant CoolPage << (C,#ADD1B2) >>
participant CoolPageNotifier << (C,#ADD1B2) >>
participant PageParametersProxy << (C,#ADD1B2) >>
participant NavigationNotifier << (C,#ADD1B2) >>
participant BrowserHistory #A9DCDF

Bob -> CoolPage : applies filter value
activate CoolPage

CoolPage -> CoolPageNotifier : filterBySomeValue(value)
activate CoolPageNotifier

CoolPageNotifier --> CoolPageNotifier : applies filter value
CoolPageNotifier --> CoolPage : notifyListeners()
CoolPageNotifier --> CoolPage : updated data
CoolPage --> Bob : updated UI
deactivate CoolPage

CoolPageNotifier --> CoolPageNotifier : updates page parameters

CoolPageNotifier -> PageParametersProxy : pageParameters
deactivate CoolPageNotifier
activate PageParametersProxy

PageParametersProxy -> NavigationNotifier : handlePageParametersUpdates(currentDeepLinks)
deactivate PageParametersProxy
activate NavigationNotifier

NavigationNotifier -> BrowserHistory : replaceState(location)
deactivate NavigationNotifier

activate BrowserHistory

BrowserHistory --> Bob : updates URL with query parameters
deactivate BrowserHistory

@enduml
