@startuml updating_deep_links_sequence_diagram
skinparam ParticipantPadding 20
skinparam BoxPadding 10

actor Bob

participant SomePage << (C,#ADD1B2) >>
participant SomePageNotifier << (C,#ADD1B2) >>
participant PageParametersProxy << (C,#ADD1B2) >>
participant NavigationNotifier << (C,#ADD1B2) >>
participant BrowserHistory #A9DCDF

Bob -> SomePage : applies filter value
activate SomePage

SomePage -> SomePageNotifier : filterBySomeValue(value)
activate SomePageNotifier

SomePageNotifier --> SomePageNotifier : applies filter value
SomePageNotifier --> SomePage : notifyListeners()
SomePageNotifier --> SomePage : updated data
SomePage --> Bob : updated UI
deactivate SomePage

SomePageNotifier --> SomePageNotifier : updates page parameters

SomePageNotifier -> PageParametersProxy : pageParameters
deactivate SomePageNotifier
activate PageParametersProxy

PageParametersProxy -> NavigationNotifier : handlePageParametersUpdates(currentDeepLinks)
deactivate PageParametersProxy
activate NavigationNotifier

NavigationNotifier -> BrowserHistory : replaceState(location)
deactivate NavigationNotifier

activate BrowserHistory

BrowserHistory --> Bob : updates URL with query parameters
deactivate BrowserHistory

@enduml
