@startuml update_feature_integration_component_diagram

skinparam componentStyle rectangle

legend top left
    | Color | Arrow type |
    |<#B70033>| Existing relationship |
    |<#Green>| New relationship |
endlegend

component "Metrics CLI" as Cli
component "Update"
component "Deploy"
component "Doctor"
component Cloud

Cli -[#Green]-* Update
Cli --* Deploy
Cli --* Doctor

Update -[#Green]-> Cloud : [redeploys a new version of components]
Deploy --> Cloud : [deploys components]

@enduml
