@startuml update_command_sequence_diagram

skinparam ParticipantPadding 20
skinparam BoxPadding 10

actor Bob

box Update Command
participant MetricsCliRunner
participant UpdateCommand
participant Updater
participant FirebaseService
participant GitService
participant NpmService
participant FlutterService
participant SentryService
participant PathsFactory
participant UpdateConfigFactory
end box

participant FileHelper

Bob -> MetricsCliRunner ++ : run update command
MetricsCliRunner -> UpdateCommand ++ : run()

UpdateCommand -> UpdateConfigFactory ++ : create(configPath)
UpdateConfigFactory --> UpdateCommand -- : parsed config

UpdateCommand -> Updater ++ : update(config)

Updater -> FileHelper ++: createTempDirectory()
FileHelper --> Updater --: directory has been created

Updater -> PathsFactory ++: create()
PathsFactory --> Updater --: Paths has been created

Updater -> GitService ++ : checkout(repoUrl, srcPath)
GitService --> Updater -- : checkout finished

Updater -> NpmService ++ : installDependencies(firebasePath)
NpmService --> Updater -- : dependencies have been installed

Updater -> NpmService ++ : installDependencies(firebaseFunctionsPath)
NpmService --> Updater --: dependencies have been installed

Updater -> FlutterService ++ : build(appPath)
FlutterService --> Updater -- : build finished

Updater --> Updater : check if the SentryConfig attribute is null
alt SentryConfig is null
Updater --> Updater : Skip Sentry setup

else SentryConfig is not null

Updater -> SentryService ++ : createRelease(sentryRelease, sourceMaps, sentryAuthToken)
SentryService --> Updater -- : SentryRelease has been created
end

Updater -> FileHelper ++ : getFile(metricsConfigPath)
FileHelper --> Updater -- : config file
Updater -> FileHelper ++ : replaceEnvironmentVariables(config, options)
FileHelper --> Updater -- : config has been updated

Updater -> FirebaseService ++ : deployFirestore(firestorePath)
FirebaseService --> Updater -- : firestore has been deployed

Updater -> FirebaseService ++ : deployHosting(projectId, target, appPath)
FirebaseService --> Updater -- : hosting has been deployed

Updater --> Updater : delete directory
Updater --> UpdateCommand --: update finished
UpdateCommand --> MetricsCliRunner --: command finished
MetricsCliRunner --> Bob -- : terminate

@enduml
