@startuml view_model_usage_diagram

package dashboard.presentation {
    package widgets {
        class ProjectTile {
            projectTileViewModel : ProjectTileViewModel
            build(BuildContext) : Widget
        }

        class Coverage {
            coverage : CoverageViewModel
            build(BuildContext) : Widget
        }

        class Stability {
            stability : CoverageViewModel
            build(BuildContext) : Widget
        }

        class BuildNumber {
            buildNumber : BuildNumberViewModel
            build(BuildContext) : Widget
        }

        class PerformanceGraph {
            performance : PerformanceViewModel
            build(BuildContext) : Widget
        }
    }

    package view_models {
        class ProjectTileViewModel {
            coverage : CoverageViewModel
            stability : StabilityViewModel
            performance : PerformanceViewModel
            buildNumber : BuildNumberViewModel
            lastBuildStatus : BuildStatus
            projectName : String
        }

        class PercentViewModel {
            value : double
        }

        class CoverageViewModel {}

        class StabilityViewModel {}

        class PerformanceViewModel {
            points : List<Point>
        }

        class BuildNumberViewModel {
            numberOfBuildes : int
        }
    }
}

package common.presentation.widgets {
    class CirclePercentage {
        value: double
        other style-related fields
        build(BuildContext) : Widget
    }

    class SparklineGraph {
        points : List<Point>
    }
}

CoverageViewModel --|> PercentViewModel
StabilityViewModel --|> PercentViewModel

ProjectTileViewModel "**1**" o.up.. "**0..1**" BuildNumberViewModel
ProjectTileViewModel "**1**" o.up.. "**0..1**" PerformanceViewModel
ProjectTileViewModel "**1**" o.up.. "**0..1**" CoverageViewModel
ProjectTileViewModel "**1**" o.up.. "**0..1**" StabilityViewModel

ProjectTile ..> Coverage : uses
ProjectTile ..> Stability : uses
ProjectTile ..> BuildNumber : uses
ProjectTile ..> PerformanceGraph : uses

PerformanceGraph .up.> SparklineGraph : uses
Coverage .up.> CirclePercentage : uses
Stability .up.> CirclePercentage : uses

ProjectTile ..> ProjectTileViewModel : uses
Coverage ..> CoverageViewModel : uses
Stability ..> StabilityViewModel : uses
BuildNumber ..> BuildNumberViewModel : uses
PerformanceGraph ..> PerformanceViewModel : uses

@enduml
