@startuml theme_data_class_diagram

package data {
    package model.deserializer {
        class CoolEntityDeserializer <<Serializable>> {
            fromJson(Map<String, dynamic>) : CoolEntityDeserializer
            toJson() : Map<String, dynamic>
        }
    }

    package data.repositories {
        class ConcreteCoolRepository {
            loadCoolEntities() : List<CoolEntity>
            updateCoolEntitiy(String coolId, String coolName) : void
        }
    }
}

package domain {

    package entities {
        class CoolEntity {
            coolId : String
            coolName : String
        }
    }

    package usecases {
        package parameters {
            class CoolParameters {
                coolId : String
                coolName : String
            }
        }

        class LoadCoolEntitiesUseCase {
            call() : List<CoolEntity>
        }

        class UpdateCoolEntityUseCase {
            call(CoolParameters params) : void
        }
    }

    package repositories {
        interface CoolRepository {
            loadCoolEntities() : List<CoolEntity>
            updateCoolEntitiy(String coolId, String coolName) : void
        }
    }
}

package presentation {
    package view_models {
        class CoolTileViewModel {
            coolName : String
        }
    }

    package pages {
        class CoolPage {
            build(BuildContext) : Widget
        }
    }

    package state {
        class CoolNotifier {
            coolModels : List<CoolTileViewModel>

            loadCoolModels() : void
            updateCoolModel(CoolTileViewModel) : void
        }
    }

    package strings {
        class CoolStrings {}
    }

    package widgets {
        class CoolTile {
            build(BuildContext) : Widget
        }

        class CoolTable {
            build(BuildContext) : Widget
        }
    }

}

ConcreteCoolRepository ..|> CoolRepository
ConcreteCoolRepository ..> CoolEntityDeserializer : uses

CoolRepository ..> CoolEntity : provides

CoolEntityDeserializer --|> CoolEntity

LoadCoolEntitiesUseCase *.. CoolRepository
UpdateCoolEntityUseCase *.. CoolRepository
LoadCoolEntitiesUseCase .up.> CoolEntity : provides
UpdateCoolEntityUseCase ..> CoolParameters : uses

CoolNotifier *.. UpdateCoolEntityUseCase
CoolNotifier *.. LoadCoolEntitiesUseCase
CoolNotifier ..> CoolTileViewModel : provides

CoolPage ..> CoolNotifier : uses
CoolPage ..> CoolTile : uses
CoolPage ..> CoolTable : uses
CoolTile ..> CoolTileViewModel : uses

pages .right.> strings : uses
widgets .up.> strings : uses

@enduml