@startuml firestore_create_builds_aggregation_sequence_diagram
    skinparam ParticipantPadding 20
    skinparam BoxPadding 10

    participant API

    database Firestore

    participant "Firestore Cloud Functions" as FCF

    API -> Firestore : creates a Build
    activate Firestore

    Firestore -> FCF : emits an onCreate event on a build collection
    activate FCF

    FCF -> FCF : triggers an onCreate event handler
    
    FCF -> Firestore : increases a counter inside the 'builds_per_day' collection

    alt Firestore Cloud Functions onCreate handler fails
        FCF -> FCF : function fails
        FCF -> Firestore : adds information about an aggregation fail to the 'tasks' collection
    end

    deactivate FCF
    deactivate Firestore

@enduml
