@startuml metrics_widgets_structure_diagram

package "widgets" {
  
  package "theme" {
    [Metrics Theme]
  }

  package "base" {  
    [Base Widgets]
  }

  package "button" {
    [Metrics Button] --> [Base Widgets] : uses
    [Metrics Button] --> [Metrics Theme] : uses
  }

  package "toast" {
    [Metrics Toast] -up-> [Base Widgets] : uses
    [Metrics Toast] -up-> [Metrics Theme] : uses
  }
   
}

@enduml
