@startuml metrics_storybook_web_relation_diagram

package "metrics" {
  package "widgets" {  
    [Metrics Storybook UI] ..> [Metrics Widgets] : uses
  }

  package "web" {
    [Metrics Web Application UI] ..> [Metrics Widgets] : uses
  }
}

@enduml
