@startuml metrics_storybook_class_diagram

package storybook {
    package stories {
        abstract class Story {
            + name : String
            + chapters : List<Chapter>
        }

        abstract class Chapter {
            + name : String
            + controls : ChapterControls

            + build() : Widget
        }

        class ChapterControls {
            + controls : Map<String, ChapterControl>

            + addTextControl(String name, String value) : void
            + addBoolControl(String name, bool value) : void
            + addColorControl(String name, Color value) : void
            + addNumberControl(String name, Number value) : void
            + getControlValue(String name) : dynamic
        }

        class ChapterControl<T> {
            + name : String
            + value : T
        }
    }
}

Story -right-> Chapter : uses
Chapter -right-> ChapterControls : creates
ChapterControls -> ChapterControl : creates

@enduml
