@startuml metrics_storybook_class_diagram

package src {
    package widgets {
        class Storybook {
            - _stories : List<Story>

            + addStoryFor(String name) : Story
        }

        class InjectionContainer {
            + stories : List<Story>
        }

        class MetricsThemeBuilder {
            + lightTheme : MetricsThemeData
            + darkTheme : MetricsThemeData
            + builder : ThemeBuilder

            + build(BuildContext context) : Widget
        }
    }

    package state {
        class StoriesNotifier {
            + stories : List<Story>

            + void setStories(List<Story> stories) : void
        }

        class ChaptersNotifier {
            + currentChapter : Chapter

            + selectChapter(Chapter chapter) : void
            + refreshChapter() : void
        }

        class ThemeNotifier {
            + isDark : bool

            + toggleTheme() : void
        }
    }

    class Story {
        + name : String
        + chapters : List<Chapter>

        + addChapter(String name, ChapterBuilder builder) : Story
    }

    class Chapter {
        + name : String
        + options : ChapterOptions
        - _builder : ChapterBuilder

        + build() : Widget
    }

    class ChapterOptions {
        + options : Map<String, Option>

        + textOption(String name, String value) : String
        + boolOption(String name, bool value) : bool
        + colorOption(String name, Color value) : Color
        + numberOption(String name, Number value) : Number
    }

    class Option<T> {
        + name : String
        + value : T
    }
}

Storybook -> InjectionContainer : creates and provides a list of stories
Storybook -left-> MetricsThemeBuilder : creates
InjectionContainer -up-> StoriesNotifier : creates
InjectionContainer -up-> ChaptersNotifier : creates
InjectionContainer -up-> ThemeNotifier : creates
Storybook -down-> Story : uses
Story -right-> Chapter : uses
Chapter -right-> ChapterOptions : creates
ChapterOptions -> Option : creates
@enduml
