@startuml metrics_storybook_class_diagram

package storybook {
    package stories {
        abstract class Story {
            + name : String
            + chapters : List<Chapter>
        }

        abstract class Chapter {
            + name : String
            + controls : ChapterControls

            + build() : Widget
        }

        class ChapterControls {
            + controls : Map<String, ChapterControl>

            + textControl(String name, String value) : String
            + boolControl(String name, bool value) : bool
            + colorControl(String name, Color value) : Color
            + numberControl(String name, Number value) : Number
        }

        class ChapterControl<T> {
            + name : String
            + value : T
        }
    }
}

Story -right-> Chapter : uses
Chapter -right-> ChapterControls : creates
ChapterControls -> ChapterControl : creates

@enduml
