@startuml metrics_storybook_architecture_components_diagram

skinparam componentStyle rectangle

component "Metrics Storybook" as MS

component "Story (e.g., Buttons)" as ButtonsStory
component "Chapter (e.g., Positive Button)" as PositiveButtonChapter

component "Story (e.g., Toasts)" as ToastsStory
component "Chapter (e.g., Positive Toast)" as PositiveToastChapter
component "Chapter Controls" as PositiveToastChapterControls
component "Text Control (e.g., text input)" as FirstPositiveToastChapterTextControl
component "Bool Control (e.g., checkbox)" as SecondPositiveToastChapterBoolControl
component "Chapter (e.g., Negative Toast)" as NegativeToastChapter
component "Chapter Controls" as NegativeToastChapterControls
component "Text Control (e.g., text input)" as FirstNegativeToastChapterTextControl
component "Bool Control (e.g., checkbox)" as SecondNegativeToastChapterBoolControl

MS -down-> ButtonsStory
MS -down-> ToastsStory

ButtonsStory -down-> PositiveButtonChapter

ToastsStory -down-> PositiveToastChapter
PositiveToastChapter -down-> PositiveToastChapterControls
PositiveToastChapterControls -down-> FirstPositiveToastChapterTextControl
PositiveToastChapterControls -down-> SecondPositiveToastChapterBoolControl

ToastsStory -down-> NegativeToastChapter
NegativeToastChapter -down-> NegativeToastChapterControls
NegativeToastChapterControls -down-> FirstNegativeToastChapterTextControl
NegativeToastChapterControls -down-> SecondNegativeToastChapterBoolControl

@enduml
