@startuml buildkite_sequence_diagram
    skinparam ParticipantPadding 20
    skinparam BoxPadding 10

    actor Bob

    box Github
        participant Repository
    endbox

    box Buildkite
        participant "Awesome pipeline"
        participant "Sync pipeline"
        participant "CI Integration tool"
    endbox

    database "Firestore" as FS

    Bob -> Repository : Pushes commit to master
    activate Repository

    Repository -> "Awesome pipeline" : Webhook triggers pipeline
    deactivate Repository
    activate "Awesome pipeline"

    "Awesome pipeline" -> "Awesome pipeline" : Performs build
    "Awesome pipeline" -> "Sync pipeline" : Triggers Sync pipeline
    deactivate "Awesome pipeline"
    activate "Sync pipeline"

    "Sync pipeline" -> "Sync pipeline" : Creates integration_config.yml
    "Sync pipeline" -> "CI Integration tool" : Runs sync command
    activate "CI Integration tool"

    "CI Integration tool" -> FS : Adds new build data

    "CI Integration tool" --> "Sync pipeline" : Sync command finishes
    deactivate "CI Integration tool"

    "Sync pipeline" --> Bob : Build data export finishes
    deactivate "Sync pipeline"
@enduml
