@startuml buildkite_sequence_diagram

actor Bob

box "Buildkite" #LightBlue

participant Pipeline
collections Steps
participant Agent

participant Build
end box

database SourceControl


Bob --> Pipeline : Creates
Bob --> Steps : Defines
Bob --> Agent: Creates

Pipeline --> SourceControl : Connects

SourceControl --> Pipeline : Notifies to run the Build
Pipeline --> Agent : Use agent to run the Build

Agent --> Build : Runs

Bob <-- Build : Build result

@enduml
