# A template for ci_integrations config with the Firestore integration as a `destination`.
# Consider the following links to familiarize yourself with Firebase projects and Cloud Firestore:
# - https://firebase.google.com/docs/projects/learn-more
# - https://firebase.google.com/docs/auth
# - https://firebase.google.com/docs/firestore

source:
# Add your source config here.

destination:
  # The `firestore` key defines that the following destination config stands for Firestore integration.
  firestore:

    # A unique identifier of the Firebase project you want to use to store builds data.
    #
    # You can obtain the identifier of your project using the Firebase Console: https://console.firebase.google.com.
    # All Firebase projects you have access to are displayed as tiles on the Console page.
    # Each tile's title stands for the project name and the subtitle stands for this project's identifier.
    # Also, you can find your project ID on the `Settings` page of your project -
    # the identifier is after the `Project ID` label under the `Your project` section.
    #
    # Moreover, you can use a link to the Firebase project to know its identifier.
    # It comes right after the `project` path segment. For example:
    # `https://console.firebase.google.com/u/0/project/<PROJECT_ID>/overview`
    firebase_project_id: ...

    # An email of the Firebase user.
    #
    # This email is used to authorize within the Firebase project defined
    # using Firebase Authorization with password sign-in method.
    # The user with the given email must exist and no synchronization
    # happens if authorization is failed.
    firebase_user_email: ...

    # A password of the Firebase user.
    #
    # Together with the given email, this password is used to authorize
    # within the Firebase project defined using Firebase Authorization with password sign-in method.
    firebase_user_pass: ...

    # A Firebase API key that is used to access your project using Firebase API.
    #
    # You can obtain the web API key on the `Settings` page of your Firebase project.
    # The key is placed after the `Web API key` under the `Your project` section.
    firebase_web_api_key: ...

    # A unique identifier of the Metrics Project in the Firestore database.
    #
    # This identifier is used to associate builds data with the Metrics project from the Firestore database.
    # All builds synchronized will be related to the project with the identifier specified using this field.
    #
    # You can obtain the Metrics project identifier in the Firebase Console on the `Cloud Firestore` page
    # under the `Data` tab. There, you can open the `projects` collection and search for your project
    # using filters by the `name` field.
    metrics_project_id: ...
