@startuml firestore_emulator_class_diagram

package test_driver {
    class FlutterWebDriver {
        - _args : DriverTestArguments
        - _processManager : ProcessManager
        + startDriverTests : Future<void>  
    }

    package arguments {
        package parser {
            class DriverTestArgumentsParser {
                - static const _useFirestoreEmulatorFlagName : String
                - static const _firestoreEmulatorPortOptionName : String
                - _configureParser() : void
                + parseArguments(List<String> args) : DriverTestArguments
            }
        } 

        package model {
            class DriverTestArguments {
                + firestoreEmulator : FirestoreEmulator
            }

            class FirestoreEmulator {
                + static useFirestoreEmulatorEnvVariableName : String
                + static firestorePortEnvVariableName : String

                + useEmulator : bool
                + port : String

                + factory fromEnvironment()
                + toMap() : Map<String, String>
            }
        }
    }

    package cli {
        package emulator {
            package runner {
                class FirebaseEmulatorRunner {
                    + port : int
                    + statusRequestUrl : String
                    + isAppStarted : Future<void>
                }
                class FirestoreEmulatorRunner {
                    - _arguments : FirestoreEmulatorCommand
                    + args : List<String>
                    + executableName : String
                    + statusRequestUrl : String
                    + run(String workingDir) : Future<FirestoreEmulatorProcess>
                }
            }
            package command {
                class FirebaseEmulatorCommand {
                    + static const executableName : String
                    + emulatorsStart() : void
                    + only(String emulator) : void
                }
                class FirestoreEmulatorCommand {
                    + import(String directory) : void
                }
            }
            package process {

                class FirestoreEmulatorProcess {
                    + static start(FirestoreEmulatorCommand args, String workingDir) : Future<FirestoreEmulatorProcess>
                }
            }
        }
    }

    package process_manager {
        class ProcessManager {
            + run : Future<ProcessWrapper>
        }
    }
}

FlutterWebDriver --> DriverTestArguments : uses
DriverTestArguments -> FirestoreEmulator : uses
FlutterWebDriver --> ProcessManager : creates
ProcessManager --> FirestoreEmulatorRunner : runs
FirestoreEmulatorRunner --> FirestoreEmulatorCommand : uses
FirestoreEmulatorRunner --> FirestoreEmulatorProcess : starts
FirestoreEmulatorRunner ..|> FirebaseEmulatorRunner
DriverTestArgumentsParser --> DriverTestArguments : provides
FirestoreEmulatorCommand ..|> FirebaseEmulatorCommand

@enduml
