@startuml firestore_emulator_sequence_diagram

skinparam ParticipantPadding 20
skinparam BoxPadding 10

actor Bob

participant FlutterWebDriver
participant ProcessManager
participant FirestoreEmulatorRunner
participant FirebaseProcess
participant FlutterDriveProcessRunner
participant Application
participant FirestoreEmulatorConfig
participant FirestoreInstance

Bob -> FlutterWebDriver : runs tests
activate FlutterWebDriver

FlutterWebDriver -> ProcessManager : creates
activate ProcessManager
deactivate FlutterWebDriver

ProcessManager -> FirestoreEmulatorRunner : run()
activate FirestoreEmulatorRunner


FirestoreEmulatorRunner -> FirebaseProcess : start()
activate FirebaseProcess
deactivate FirestoreEmulatorRunner

FirebaseProcess --> FirebaseProcess : runs the emulator (firebase emulators:start --only firestore)

FirebaseProcess -> ProcessManager : emulator is started
deactivate FirebaseProcess

ProcessManager -> FlutterDriveProcessRunner : run()
activate FlutterDriveProcessRunner
deactivate ProcessManager

deactivate FirebaseProcess

FlutterDriveProcessRunner -> Application : runs and test
deactivate FlutterDriveProcessRunner
activate Application

Application -> FirestoreEmulatorConfig : fromEnvironment()
activate FirestoreEmulatorConfig

FirestoreEmulatorConfig --> Application : FirestoreEmulatorConfig instance
deactivate FirestoreEmulatorConfig

Application -> FirestoreInstance : settings(localEmulatorHost)
activate FirestoreInstance

FirestoreInstance --> FirestoreInstance : points to the local emulator

Application --> Bob : tests result
deactivate FirestoreInstance
deactivate Application

@enduml
