@startuml
skinparam ParticipantPadding 20
skinparam BoxPadding 10

actor Bob

participant SomePage << (C,#ADD1B2) >>
participant SomePageNotifier << (C,#ADD1B2) >>
participant DeepLinksDispatcher << (C,#ADD1B2) >>
participant DeepLinksNotifier << (C,#ADD1B2) >>
participant NavigationNotifier << (C,#ADD1B2) >>

Bob -> SomePage : applies filter value
activate SomePage

SomePage -> SomePageNotifier : filterBySomeValue(value)
activate SomePageNotifier

SomePageNotifier --> SomePageNotifier : applies filter value
SomePageNotifier --> SomePage : notifyListeners()
SomePageNotifier --> SomePage : updated view models
SomePage --> Bob : updates UI elements
deactivate SomePage


SomePageNotifier --> SomePageNotifier : updateDeepLinks()

SomePageNotifier -> DeepLinksDispatcher : notifyListeners()
deactivate SomePageNotifier
activate DeepLinksDispatcher

DeepLinksDispatcher -> DeepLinksNotifier : handlePageDeepLinks(pageDeepLinks)
activate DeepLinksNotifier

DeepLinksNotifier -> DeepLinksDispatcher : notifyListeners()
deactivate DeepLinksNotifier

DeepLinksDispatcher -> NavigationNotifier : saveDeepLinks(currentDeepLinks)
deactivate DeepLinksDispatcher
activate NavigationNotifier

NavigationNotifier --> NavigationNotifier : replaceState()
NavigationNotifier --> Bob : sees updated URL with deep links
deactivate NavigationNotifier

@enduml
