targets:
  $default:
    sources:
      - lib/**
      - $package$
    builders:
      build_node_compilers|entrypoint:
        generate_for:
          - lib/**
        options:
          compiler: dart2js
