@startuml build_days_data_layer_class_diagram

package common {
    package domain {
        package repositories {
            interface BuildDayRepository {
                + projectBuildDaysFromDateStream(String projectId, DateTime from) : Stream<List<BuildDay>>
            }
        }

        package entities {
            class BuildDay {
                + projectId : String
                + successful: int
                + failed: int
                + unknown: int
                + inProgress: int
                + totalDuration : int
                + day : Timestamp
            }
        }
    }

    package data {
        package repositories as data_repositories {
            class FirestoreBuildDayRepository {}
        }

        package deserializer {
            class BuildDayDataDeserializer {
                + static fromJson(Map<String, dynamic> json) : BuildDay
            }
        }
    }
}


FirestoreBuildDayRepository ..|> BuildDayRepository
FirestoreBuildDayRepository --> BuildDayDataDeserializer : uses

BuildDayDataDeserializer --> BuildDay : uses

@enduml
