@startuml build_days_presentation_layer_class_diagram
    package common {
        package domain {
            package entities {
                package metrics {
                    class BuildNumberMetric {
                        + numberOfBuilds : int
                    }
                    class BuildPerformance {
                          + date : DateTime
                          + duration: Duration
                    }
                    class PerformanceMetric {
                        + buildsPerformance : DateTimeSet<BuildPerformance>
                        + averageBuildDuration : Duration
                    }
                    class BuildDayProjectMetrics {
                        + buildNumberMetric : BuildNumberMetric
                        + performanceMetric : PerformanceMetric
                    }
                }
            }

            package usecases {
                class ReceiveBuildDayProjectMetricsUpdates {
                    + call(BuildDayParam params) : Stream<BuildDayProjectMetrics>
                }
            }
        }
    }

    package dashboard {
        package presentation.state {
            class ProjectMetricsNotifier {
                - _receiveBuildDayProjectMetricsUpdates : ReceiveBuildDayProjectMetricsUpdates
                - _subscribeToBuildDayMetrics(String projectId) : void
            }
        }
    }

    ProjectMetricsNotifier -> ReceiveBuildDayProjectMetricsUpdates : uses
    ReceiveBuildDayProjectMetricsUpdates -> BuildDayProjectMetrics : provides
    ProjectMetricsNotifier -> BuildDayProjectMetrics : uses

    BuildDayProjectMetrics -> BuildNumberMetric : uses
    BuildDayProjectMetrics -> PerformanceMetric : uses
    PerformanceMetric -> BuildPerformance : uses
    
@enduml
