@startuml builds_aggregation_data_layer_class_diagram

package common.domain.repository {
    interface BuildsAggregationRepository {}
}

package common.domain.entities {
    class BuildsAggregation {}
}

package common.data {
    package repository {
        class FirestoreBuildsAggregationRepository {}
    }

    package models {
        class BuildsAggregationData {
            + Map<String, dynamic> toJson()
            + factory fromJson(Map<String, dynamic> json)
        }
    }
}

package core.src.data.model {
    class DataModel {}
}

FirestoreBuildsAggregationRepository ..|> BuildsAggregationRepository
FirestoreBuildsAggregationRepository --> BuildsAggregationData : uses

BuildsAggregationData --> BuildsAggregation
BuildsAggregationData ..|> DataModel

@enduml
