@startuml builds_aggregation_data_layer_class_diagram

package common.domain.repository {
    interface FailedBuildsAggregationRepository {}
}

package common.domain.entities {
    class FailedBuildsAggregation {}
}

package common.data {
    package repository {
        class FirestoreFailedBuildsAggregationRepository {}
    }

    package models {
        class FailedBuildsAggregationData {
            + Map<String, dynamic> toJson()
            + factory fromJson(Map<String, dynamic> json)
        }
    }
}

package core.src.data.model {
    class DataModel {}
}

FirestoreFailedBuildsAggregationRepository ..|> FailedBuildsAggregationRepository
FirestoreFailedBuildsAggregationRepository --> FailedBuildsAggregationData : uses

FailedBuildsAggregationData --> FailedBuildsAggregation
FailedBuildsAggregationData ..|> DataModel

@enduml
