@startuml add_coverage_data_sequence_diagram
'https://plantuml.com/sequence-diagram

skinparam SequenceMessageAlignment center
skinparam ParticipantPadding 80

participant BuildsSyncStage
participant SourceClient

?-> BuildsSyncStage ++ : addCoverageData(//builds//)
note right of BuildsSyncStage: //final result = []//
||8||
loop for each //build// in //builds//
    BuildsSyncStage -> SourceClient ++ : fetchCoverage(//build//)
    return //coverage//
    note right of BuildsSyncStage: //final newBuild = build.copyWith(coverage: coverage)//
    note right of BuildsSyncStage: //result.add(newBuild)//
end
||8||
return result

@enduml
