@startuml coverage_data_model_class_diagram

package core.src {
    package domain {
        package value_objects {
            class Percent {
                value: double
            }
        }

        package entities {
            class Coverage {
                percent: Percent
            }
        }
    }


    package data.model {
        class CoverageData {
            Map<String, dynamic> toJson()
            factory fromJson()
        }

        interface DataModel {
            {abstract} Map<String, dynamic> toJson()
        }
    }
}

Coverage -> Percent : uses
CoverageData -|> Coverage

CoverageData ..|> DataModel


@enduml
