@startuml ci_integrations_config_validator_sequence_diagram

skinparam ParticipantPadding 20
skinparam BoxPadding 10

actor Bob

participant "CI Integrations"
participant CiIntegrationsRunner
participant SyncCommand
participant ConfigValidatorFactory
participant ConfigValidator
participant ValidationDelegate
participant CoolIntegrationClient

Bob -> "CI Integrations" : runs sync
activate "CI Integrations"

"CI Integrations" -> CiIntegrationsRunner: run(List<String> arguments)
activate CiIntegrationsRunner

CiIntegrationsRunner -> SyncCommand: run()
deactivate CiIntegrationsRunner
activate SyncCommand

SyncCommand -> SyncCommand : creates source and destination parties
SyncCommand -> SyncCommand : parses source and destination configs

SyncCommand -> ConfigValidatorFactory : create()
activate ConfigValidatorFactory

ConfigValidatorFactory --> SyncCommand : configValidator
deactivate ConfigValidatorFactory

SyncCommand -> ConfigValidator : validate(config)
activate ConfigValidator


ConfigValidator -> ValidationDelegate : tries to authenticate with the given credentials
activate ValidationDelegate

ValidationDelegate -> CoolIntegrationClient : authenticate()
activate  CoolIntegrationClient
CoolIntegrationClient --> ValidationDelegate : InteractionResult

ValidationDelegate --> ConfigValidator : authentication result
ConfigValidator -> ValidationDelegate : tries to validate other config fields
ValidationDelegate -> CoolIntegrationClient : anotherMehod()
CoolIntegrationClient --> ValidationDelegate : InteractionResult
ValidationDelegate --> ConfigValidator : other validation result

deactivate ValidationDelegate

alt config is valid

    ConfigValidator --> SyncCommand : config is valid
    SyncCommand -> SyncCommand : continues the sync command
    SyncCommand --> Bob : sync was successful

else config is not valid

    ConfigValidator -> ConfigValidator : creates exception message
    ConfigValidator --> SyncCommand : throw ""ConfigValidationException(message)""
    SyncCommand --> Bob : sync failed

end

deactivate ConfigValidator

deactivate "CI Integrations"
deactivate SyncCommand

@enduml
