@startuml resync_builds_stage_sequence_diagram
'https://plantuml.com/sequence-diagram

skinparam SequenceMessageAlignment center

participant InProgressBuildsSyncStage
participant SourceClient
participant DestinationClient

?-> InProgressBuildsSyncStage ++ : call(//config//)
|||
InProgressBuildsSyncStage -> DestinationClient ++ : fetchBuildsWithStatus(//config.destinationProjectId, BuildStatus.inProgress//)
return //buildsInProgress//
note right of InProgressBuildsSyncStage: //final buildsUpdate = []//
loop for each //build// in //buildsInProgress//
    InProgressBuildsSyncStage -> InProgressBuildsSyncStage ++ : _syncInProgressBuild(//config, build//)
    return //refreshedBuild//
    |||
    opt //refreshedBuild// != null
        note right of InProgressBuildsSyncStage: //buildsUpdate.add(refreshedBuild)//
    end
end
|||
opt //config.coverage//
    ||8||
    InProgressBuildsSyncStage -> InProgressBuildsSyncStage ++ : //addCoverageData(buildsUpdate)//
    return //buildsUpdate//
    ||8||
end

InProgressBuildsSyncStage -> DestinationClient ++ : updateBuilds(//config.destinationProjectId, buildsUpdate//)
return void

return InteractionResult

@enduml
