@startuml resync_builds_stage_activity_diagram
'https://plantuml.com/activity-diagram-beta
skinparam ConditionEndStyle hline

:destination.fetchBuildsWithStatus(BuildStatus.inProgress) -> **buildsInProgress**;
note left
    fetch //builds// where
    //state// is //in progress//
end note

repeat
    :source.fetchBuild() -> **build**;

    if (should force timeout) then (yes)
        :force time out -> **newBuild**;
        note left
            controlled by CLI option
            //--in-progress-timeout//
            defaults to //120 minutes//
        end note
    else (no)
        :process **build** -> **newBuild**;
    endif

    :**result**.add(**newBuild**);
repeatwhile (for each in **buildsInProgress**)

:fetch coverage for builds if necessary;
:destination.updateBuilds(**result**);
note left
    for each //build// in //result//
    set //new data//
end note

end

@enduml
