@startuml sync_stage_activity_diagram
'https://plantuml.com/activity-diagram-beta
skinparam ConditionEndStyle hline

:destination.fetchLastBuild() -> **lastBuild**;

if (**lastBuild** is **null**) then (yes)
    :source.fetchBuilds() -> **result**;
else (no)
    :source.fetchBuildsAfter(**lastBuild**) -> **result**;
endif

if (should fetch coverage) then (yes)
    partition "for each **build** in **result**" {
        :source.fetchCoverage(**build**) -> **coverage**;
        :update **build** with **coverage**;
    }
else (no)
endif
note right
    controlled by CLI flag
    //--coverage// or //--no-coverage//
    defaults to //on// (//--coverage//)
end note

:destination.addBuilds(**result**);
note right
    Builds possible states:
    - **in progress**
    - successful
    - failed
    - unknown
end note

end

@enduml
