@startuml resync_in_progress_sequence_diagram
'https://plantuml.com/sequence-diagram

skinparam SequenceMessageAlignment center

participant CiIntegration
participant SourceClient
participant DestinationClient

?-> CiIntegration ++ : _syncBuilds(//config//)
|||
CiIntegration -> DestinationClient ++ : fetchLastBuild(//config.destinationProjectId//)
return //lastBuild//

alt //lastBuild == null//
    ||8||
    CiIntegration -> SourceClient ++: fetchBuilds(//config.sourceProjectId, config.initialSyncLimit//)
    return //builds//
    ||8||
else  //lastBuild != null//
    ||8||
    CiIntegration -> SourceClient ++: fetchBuildsAfter(//config.sourceProjectId, lastBuild//)
    return //builds//
    ||8||
end

opt config.coverage
    ||8||
    CiIntegration -> CiIntegration ++ : //_addCoverageData(builds)//
    loop for each //build// in //builds//
        CiIntegration -> SourceClient ++ : fetchCoverage(//build//)
        return //percent//
        note right of CiIntegration: add //percent// value to //build// and save to the resulting list
    end
    return builds
    ||8||
end

CiIntegration -> DestinationClient ++ : addBuilds(//config.destinationProjectId, builds//)
return void

return InteractionResult

@enduml
