@startuml resync_in_progress_sequence_diagram
'https://plantuml.com/sequence-diagram

skinparam SequenceMessageAlignment center

participant NewBuildsSyncStage
participant SourceClient
participant DestinationClient

?-> NewBuildsSyncStage ++ : call(//config//)
|||
NewBuildsSyncStage -> DestinationClient ++ : fetchLastBuild(//config.destinationProjectId//)
return //lastBuild//

alt //lastBuild == null//
    ||8||
    NewBuildsSyncStage -> SourceClient ++: fetchBuilds(//config.sourceProjectId, config.initialSyncLimit//)
    return //builds//
    ||8||
else  //lastBuild != null//
    ||8||
    NewBuildsSyncStage -> SourceClient ++: fetchBuildsAfter(//config.sourceProjectId, lastBuild//)
    return //builds//
    ||8||
end

opt //config.coverage//
    ||8||
    NewBuildsSyncStage -> NewBuildsSyncStage ++ : //addCoverageData(builds)//
    return builds
    ||8||
end

NewBuildsSyncStage -> DestinationClient ++ : addBuilds(//config.destinationProjectId, builds//)
return void

return InteractionResult

@enduml
