name: guardian
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  args: ^1.5.2
  slack: ^2.0.0
  http: ^0.11.2

dev_dependencies:
  lint: ^1.1.1
  test: ^1.6.0
