name: guardian
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  args: ^1.5.2
  http: ^0.11.2
  meta: ^1.1.8
  slack: ^2.0.0
  yaml: ^2.2.0
  xml: ^3.7.0

dev_dependencies:
  lint: ^1.1.1
  test: ^1.6.0
