name: guardian
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  args: ^1.5.2
  http: ^0.11.2
  meta: ^1.1.8
  yaml_map:
    git:
      url: https://github.com/Flank/flank-dashboard.git
      path: yaml_map
  xml: ^3.7.0
  equatable: ^1.0.3

dev_dependencies:
  lint: ^1.1.1
  test: ^1.6.0
