source:
  github_actions:
    workflow_identifier: coverage_converter_actions.yml
    repository_name: monorepo
    repository_owner: platform-platform
    access_token: $GITHUB_TOKEN
    job_name: Coverage Converter MacOS Actions
    coverage_artifact_name: coverage_report
destination:
  firestore:
    firebase_project_id: metrics-d9c67
    firebase_user_email: $WEB_APP_USER_EMAIL
    firebase_user_pass: $WEB_APP_USER_PASSWORD
    firebase_public_api_key: $CI_INTEGRATIONS_FIREBASE_API_KEY
    metrics_project_id: coverage_converter
