@startuml metrics_logger_initialize_sequence_diagram

skinparam ParticipantPadding 20
skinparam BoxPadding 10

actor Bob

participant MetricsApp << (C,#ADD1B2) >>
participant MetricsLogger << (C,#ADD1B2) >>
participant CoolLoggerWriter << (C,#ADD1B2) >>

Bob -> MetricsApp : enters the application
activate MetricsApp

MetricsApp -> CoolLoggerWriter : create new writer
activate CoolLoggerWriter
return loggerWriter

opt collect default contexts
    MetricsApp -> MetricsApp : collect contextsMap
end

MetricsApp -> MetricsLogger : initilize(loggerWriter, contextsMap)
activate MetricsLogger
opt if contextsMap is specified
    loop for each entry in contextsMap
        MetricsLogger -> CoolLoggerWriter : setContext(entry.key, entry.value)
        activate CoolLoggerWriter
        return void
    end
end

MetricsLogger -> MetricsLogger : save loggerWriter
return void

return application UI
@enduml
