@startuml feature_config_domain_layer_class_diagram.puml

package base.domain.usecases {
    interface UseCase<Type, Params> {
        call: Type
    }
}

package common.domain {
    package repository {
        interface FeatureConfigRepository {
            + Future<FeatureConfig> fetch()
        }
    }

    package entities {
        class FeatureConfig {
            + isPasswordSignInOptionEnabled : bool
            + isDebugMenuEnabled : bool
        }
    }

    package usecases {
        class FetchFeatureConfigUseCase {
            + Future<FeatureConfig> call(FeatureConfigParam params)
        }

        package parameters {
            class FeatureConfigParam {
                + isPasswordSignInOptionEnabled : bool
                + isDebugMenuEnabled : bool
            }
        }

    }
}

FetchFeatureConfigUseCase ..|> UseCase

FetchFeatureConfigUseCase -up-> FeatureConfigRepository : uses

FeatureConfigRepository --> FeatureConfig: uses

FetchFeatureConfigUseCase --> FeatureConfigParam : uses

@enduml
