@startuml feature_config_presentation_layer_class_diagram

package base.domain.usecases {
    class FetchFeatureConfigUseCase {}
}

package common.presentation {

    package state {
        class FeatureConfigNotifier {
            + isLoading : bool
            + isInitialized : bool
            + passwordSignInOptionFeatureConfigViewModel : PasswordSignInOptionFeatureConfigViewModel
            + debugMenuFeatureConfigViewModel : DebugMenuFeatureConfigViewModel

            - _featureConfig : FeatureConfig
            - _defaultFeatureConfig : FeatureConfig
            - _fetchFeatureConfigUseCase : FetchFeatureConfigUseCase

            + Future<void> initializeConfig()
            + void setDefaults(bool isPasswordSignInOptionEnabled, bool isDebugMenuEnabled)
        }
    }

    package view_models {
        abstract class FeatureConfigViewModel {
            + isEnabled: bool
        }

        class PasswordSignInOptionFeatureConfigViewModel {}

        class DebugMenuFeatureConfigViewModel {}
    }
}

package widgets {
    class CoolWidget {}
}

package pages {
    class CoolPage {}
}

CoolWidget --> FeatureConfigNotifier : uses

CoolPage --> FeatureConfigNotifier : uses

FeatureConfigNotifier --> FetchFeatureConfigUseCase : uses

FeatureConfigNotifier --> PasswordSignInOptionFeatureConfigViewModel : uses
FeatureConfigNotifier --> DebugMenuFeatureConfigViewModel : uses

PasswordSignInOptionFeatureConfigViewModel --|> FeatureConfigViewModel
DebugMenuFeatureConfigViewModel --|> FeatureConfigViewModel

@enduml
