@startuml config_validator_sequence_diagram

skinparam ParticipantPadding 20
skinparam BoxPadding 10

actor Bob

box CI Integrations #whiteSmoke

participant "CI Integrations"
participant CiIntegrationsRunner
participant ValidateCommand
participant CoolIntegrationValidatorFactory
participant CoolIntegrationSourceValidator
participant CoolIntegrationSourceValidationDelegate
participant CoolIntegrationClient

end box

box Validation #whiteSmoke

participant ValidationResultBuilder
participant ValidationResultPrinter

end box

Bob -> "CI Integrations" : runs ""validate"" command
activate "CI Integrations"

"CI Integrations" -> CiIntegrationsRunner: run(List<String> arguments)
deactivate "CI Integrations"
activate CiIntegrationsRunner

CiIntegrationsRunner -> ValidateCommand: run()
deactivate CiIntegrationsRunner
activate ValidateCommand

ValidateCommand -> ValidateCommand : creates source and Source parties
ValidateCommand -> ValidateCommand : parses source and Source configs

ValidateCommand -> CoolIntegrationValidatorFactory : create()
activate CoolIntegrationValidatorFactory

CoolIntegrationValidatorFactory -> ValidationResultBuilder : createForTargets(List<ValidationTarget> targets)
activate ValidationResultBuilder

ValidationResultBuilder --> CoolIntegrationValidatorFactory : ValidationResultBuilder instance

CoolIntegrationValidatorFactory --> ValidateCommand : ConfigValidator instance
deactivate CoolIntegrationValidatorFactory

ValidateCommand -> CoolIntegrationSourceValidator : validate(config)
activate CoolIntegrationSourceValidator

CoolIntegrationSourceValidator -> CoolIntegrationSourceValidationDelegate : validateAuth(auth)
activate CoolIntegrationSourceValidationDelegate

CoolIntegrationSourceValidationDelegate --> CoolIntegrationSourceValidator : TargetValidationResult
CoolIntegrationSourceValidator -> ValidationResultBuilder : setResult(TargetValidationResult)

CoolIntegrationSourceValidator -> CoolIntegrationSourceValidationDelegate : validateAnotherField(anotherField)
deactivate CoolIntegrationClient

CoolIntegrationSourceValidationDelegate --> CoolIntegrationSourceValidator : TargetValidationResult
deactivate CoolIntegrationSourceValidationDelegate

CoolIntegrationSourceValidator -> ValidationResultBuilder : setResult(TargetValidationResult)
CoolIntegrationSourceValidator -> ValidationResultBuilder : build()
ValidationResultBuilder --> CoolIntegrationSourceValidator : ValidationResult instance
deactivate ValidationResultBuilder

CoolIntegrationSourceValidator --> ValidateCommand : ValidationResult
deactivate CoolIntegrationSourceValidator

ValidateCommand -> ValidationResultPrinter : .print(ValidationResult)
deactivate ValidateCommand
activate ValidationResultPrinter

ValidationResultPrinter --> Bob : prints ""validate"" command output
deactivate ValidationResultPrinter

@enduml