@startuml doctor_output_feature_component_diagram
'https://plantuml.com/component-diagram

legend top left
    | Color |  Description |
    |<#green>| New relationship |
    |<#5B95BB>| Modified relationship/component |
end legend

package "Metrics CLI" {
    component "Doctor Command" as doctor
}

package "CI Integrations" {
    component "Validate Command" as validate
}

component "Validation Output" as output #5B95BB

doctor -[#green]down-> output : uses
validate -[#5B95BB]down-> output : uses

@enduml
