@startuml doctor_output_improvements_class_diagram

package cli.lib as cli_lib {
    package cli {
        package command {
            class DoctorCommand {
                + name: String
                + doctorFactory: DoctorFactory
                + validationResultPrinter: ValidationResultPrinter

                + run(): Future<void>
            }
        }

        package doctor {
            class Doctor {
                - _coolService: CoolService
                - _dependencies: Dependencies
                + validationResultBuilder: ValidationResultBuilder

                + checkVersions(): Future<ValidationResult>
            }

            package factory as doctor_factory {
                class DoctorFactory {
                    - _servicesFactory: ServicesFactory
                    - _dependenciesFactory: DependenciesFactory

                    + create(): Doctor
                }
            }
            
            package constants {
                class DoctorConstants {
                    + {static} dependenciesPath: String
                }
            }
        }
    }

    package services {
        package common.service.model {
            enum ServiceName {
                gcloud
                git
                firebase
                flutter
                npm
                sentry
            }

            package mapper {
                class ServiceNameMapper {
                    + gcloud: String
                    + git: String
                    + firebase: String
                    + flutter: String
                    + npm: String
                    + sentry: String

                    + map(value: String): ServiceName
                    + unmap(value: Service): String
                }
            }
        }

        package cool_service {
            package adapter {
                class CoolCliServiceAdapter {
                    - _coolServiceCli: CoolServiceCli

                    + version(): Future<ProcessResult>
                }
            }

            package cli as cool_service_cli {
                class CoolServiceCli {
                    + executable: String

                    + version(): Future<ProcessResult>
                }
            }

            abstract class CoolService {
                + serviceName: ServiceName
                + version(): Future<ProcessResult>
            }
        }
    }

    package util.dependencies {
        package factory as dependencies_factory {
            class DependenciesFactory {
                + create(fromFile: String): Dependencies
            }
        }

        class Dependency {
            + recommendedVersion: String
            + installUrl: String

            + fromMap(map: Map<String, dynamic>): Dependency
        }

        class Dependencies {
            - _dependencies: Map<String, Dependency>

            + getFor(service: String): Dependency
            + fromMap(map: Map<String, dynamic>): Dependencies
        }
    }
}

DoctorCommand --> Doctor : uses
DoctorCommand -left-> DoctorFactory : uses

DoctorFactory --> Doctor : creates
DoctorFactory -up-> DependenciesFactory : uses
DoctorFactory -up-> DoctorConstants : uses

Doctor --> CoolService : uses
Doctor -right-> Dependencies : uses
Doctor -right-> Dependency : uses
Doctor --> ServiceNameMapper : uses

CoolCliServiceAdapter .up.|> CoolService
CoolCliServiceAdapter -down-> CoolServiceCli : uses

CoolService --> ServiceName : uses

DependenciesFactory --> Dependencies : creates

Dependencies --> Dependency : uses

ServiceNameMapper --> ServiceName : uses

@enduml
