@startuml validation_output_class_diagram

package core.lib.src.features.validation_output {
    package model {
        package builder {
            class ValidationResultBuilder {
                - _results: UnmodifiableMapView<ValidationTarget, TargetValidationResult>

                + setResult(result: TargetValidationResult): void
                + setEmptyResults(result: TargetValidationResult): void
                + build(): ValidationResult
            }
        }

        class ValidationTarget<T> {
            + name: String
            + description: String
        }

        class ValidationConclusion<T> {
            + name: String
            + indicator: String
        }

        class TargetValidationResult<T> {
            + data: T
            + target: ValidationTarget<T>
            + conclusion: ValidationConclusion<T>
            + description: String
            + details: Map<String, dynamic>
            + context: Map<String, dynamic>

            + copyWith(): TargetValidationResult
        }

        class ValidationResult{
            + results: UnmodifiableMapView<ValidationTarget, TargetValidationResult>
        }
    }

    package printer {
        class ValidationResultPrinter{
            - _sink: StringSink

            + print(result: ValidationResult): void
        }
    }
}

TargetValidationResult --> ValidationTarget : uses
TargetValidationResult --> ValidationConclusion : uses

ValidationResult --> TargetValidationResult : uses
ValidationResult --> ValidationTarget : uses

ValidationResultBuilder -up-> ValidationResult : builds
ValidationResultBuilder --> ValidationTarget : uses
ValidationResultBuilder -up-> TargetValidationResult : uses

ValidationResultPrinter --> ValidationConclusion : uses
ValidationResultPrinter --> ValidationTarget : uses
ValidationResultPrinter --> ValidationResult : prints

@enduml
