name: ci_integration
description: A command-line application for importing CI builds to the Metrics database.

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  args: ^1.5.3
  http: ^0.12.0+4
  meta: ^1.1.8
  equatable: ^1.1.1

dev_dependencies:
  lint: ^1.1.1
  test: ^1.14.1
  api_mock_server:
    git:
      url: https://github.com/software-platform/monorepo.git
      # TODO: before PR is merged - remove the following line
      ref: jenkins_api_integration
      path: api_mock_server
