name: ci_integration
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  args: ^1.5.3
  http: ^0.12.0+4
  meta: ^1.1.8
  equatable: ^1.1.1

dev_dependencies:
  lint: ^1.1.1
  test: ^1.14.1
