@startuml storage_version_components

skinparam defaultTextAlignment center

component "Flutter Service" as flutter_service
' component "Firebase Service" as firebase_service
component "Git Service" as git_service

component "Metrics CLI" as metrics_cli

component "Metrics Web application \l sources" as metrics_web_sources
component "Metrics Web application" as metrics_web_app

cloud "Firebase" {
    component Hosting as hosting
}

metrics_cli --> flutter_service : uses
metrics_cli -[#Green]-> flutter_service : <color:green>provides supported \n <color:green>storage version
metrics_cli --> git_service : uses

flutter_service --[#Green]-> metrics_web_app : <color:green>sets suppported\n <color:green>storage version
flutter_service ---> metrics_web_sources : uses to build\n the Metrics Web app
flutter_service ---> metrics_web_app : builds
git_service ---> metrics_web_sources : checkouts source code
metrics_web_app ---> hosting : deployed to

metrics_cli -[#Green]--> metrics_web_sources : <color:green>gets the\n <color:green> storage version

@enduml