steps:
  - label: "Enable web support"
    key: "configure"
    commands:
      - flutter channel beta
      - flutter config --enable-web

  - label: "Flutter analyze"
    key: "analyze"
    depends_on: "configure"
    commands:
      - cd metrics/web
      - flutter analyze

  - label: "Flutter test"
    key: "tests"
    depends_on: "analyze"
    commands:
      - cd metrics/web
      - flutter test --coverage --coverage-path build/coverage.info
    artifact_paths: "metrics/web/build/coverage.info"

  - label: "Flutter driver test"
    key: "driver_tests"
    depends_on: "tests"
    commands:
      - cd metrics/web
      - flutter pub get
      - dart test_driver/main.dart --no-verbose --store-logs-to=build/logs --email=$$WEB_APP_USER_EMAIL --password=$$WEB_APP_USER_PASSWORD

  - label: "Export coverage report"
    key: "coverage"
    depends_on: "tests"
    commands:
      - curl -o coverage_converter -k https://github.com/platform-platform/monorepo/releases/download/coverage-converter-snapshot/coverage_converter_linux -L
      - chmod a+x coverage_converter
      - buildkite-agent artifact download metrics/web/build/coverage.info .
      - ./coverage_converter lcov -i metrics/web/build/coverage.info -o coverage-summary.json
    artifact_paths: "coverage-summary.json"

  - label: "Finalize build"
    key: "finalize"
    depends_on:
      - step: "coverage"
      - step: "driver_tests"
    commands:
      - echo "The build is completed."

  - label: "Trigger sync for a Web project"
    trigger: sync-pipeline
    depends_on: "finalize"
    allow_dependency_failure: true
    async: true
    build:
      env:
        PIPELINE_SLUG: "${BUILDKITE_PIPELINE_SLUG}"
        METRICS_PROJECT_ID: "buildkite_metrics_web"
