steps:
  - label: "Enable web support"
    key: "configure"
    commands:
      - flutter channel beta
      - flutter config --enable-web
    plugins:
      - docker-compose:
          config: ".buildkite/compose-files/flutter-docker-compose.yml"
          run: flutter
          workdir: /monorepo

  - label: "Flutter analyze"
    key: "analyze"
    depends_on: "configure"
    commands:
      - cd metrics/web
      - flutter analyze
    plugins:
      - docker-compose:
          config: ".buildkite/compose-files/flutter-docker-compose.yml"
          run: flutter
          workdir: /monorepo

  - label: "Flutter test"
    key: "tests"
    depends_on: "analyze"
    allow_dependency_failure: true
    commands:
      - cd metrics/web
      - flutter test --coverage --coverage-path build/coverage.info
      - coverage_converter lcov -i coverage/lcov.info -o coverage-summary.json
    plugins:
      - docker-compose:
          config: ".buildkite/compose-files/flutter-docker-compose.yml"
          run: flutter
          workdir: /monorepo
    artifact_paths:
      - "metrics/web/coverage-summary.json"

  - label: "Flutter driver test"
    key: "driver_tests"
    depends_on: "tests"
    commands:
      - cd metrics/web
      - flutter pub get
      - dart test_driver/main.dart --no-verbose --store-logs-to=build/logs --email=$$WEB_APP_USER_EMAIL --password=$$WEB_APP_USER_PASSWORD
    plugins:
      - docker-compose:
          config: ".buildkite/compose-files/flutter-docker-compose.yml"
          run: flutter
          workdir: /monorepo

  - label: "Finalize build"
    key: "finalize"
    depends_on:
      - step: "test"
      - step: "driver_tests"
    commands:
      - echo "The build is completed."

  - label: "Trigger sync for a Web project"
    trigger: sync-pipeline
    depends_on: "finalize"
    allow_dependency_failure: true
    async: true
    build:
      env:
        PIPELINE_SLUG: "${BUILDKITE_PIPELINE_SLUG}"
        METRICS_PROJECT_ID: "buildkite_metrics_web"
