steps:
  - label: "Flutter analyze"
    commands:
      - "cd metrics/web"
      - "flutter analyze"

  - wait: ~

  - label: "Flutter test"
    commands:
      - "cd metrics/web"
      - "flutter test --coverage --coverage-path build/coverage.info"
    artifact_paths: "metrics/web/build/coverage.info"

  - wait: ~

  - label: "Flutter driver test"
    commands:
      - "cd metrics/web"
      - "flutter pub get"
      - "dart test_driver/main.dart --no-verbose --store-logs-to=build/logs --email=$WEB_APP_USER_EMAIL --password=$WEB_APP_USER_PASSWORD"

  - wait: ~

  - label: "Download coverage tool"
    commands:
      - "curl -o coverage_converter -k https://github.com/platform-platform/monorepo/releases/download/coverage-converter-snapshot/coverage_converter_linux -L"
    artifact_paths: "coverage_converter"

  - wait: ~

  - label: "Export coverage report"
    commands:
      - "buildkite-agent artifact download coverage_converter ."
      - "chmod a+x coverage_converter"
      - "buildkite-agent artifact download metrics/web/build/coverage.info ."
      - "./coverage_converter lcov -i metrics/web/build/coverage.info -o coverage-summary.json"
    artifact_paths: "coverage-summary.json"