steps:
  - label: "Enable web support"
    commands:
      - flutter channel beta
      - flutter config --enable-web

  - wait: ~
    continue_on_failure: true

  - label: "Flutter analyze"
    commands:
      - cd metrics/web
      - flutter analyze

  - wait: ~
    continue_on_failure: true

  - label: "Flutter test"
    commands:
      - cd metrics/web
      - flutter test --coverage --coverage-path build/coverage.info
    artifact_paths: "metrics/web/build/coverage.info"

  - wait: ~
    continue_on_failure: true

  - label: "Flutter driver test"
    commands:
      - cd metrics/web
      - flutter pub get
      - dart test_driver/main.dart --no-verbose --store-logs-to=build/logs --email=$$WEB_APP_USER_EMAIL --password=$$WEB_APP_USER_PASSWORD

  - wait: ~
    continue_on_failure: true

  - label: "Export coverage report"
    commands:
      - curl -o coverage_converter -k https://github.com/platform-platform/monorepo/releases/download/coverage-converter-snapshot/coverage_converter_linux -L
      - chmod a+x coverage_converter
      - buildkite-agent artifact download metrics/web/build/coverage.info .
      - ./coverage_converter lcov -i metrics/web/build/coverage.info -o coverage-summary.json
    artifact_paths: "coverage-summary.json"

  - wait: ~
    continue_on_failure: true

  - trigger: sync-metrics-web-pipeline
    async: true
