steps:
  - label: "Performing sync for a project"
    key: "start"
    commands:
      - echo $$PIPELINE_SLUG
      - echo $$METRICS_PROJECT_ID

  - label: "Sync builds"
    depends_on: "start"
    commands:
      - cd .metrics/buildkite
      - eval "echo \"$(sed 's/"/\\"/g' integration_config.yml)\"" >> integration.yml
      - ci_integrations sync --config-file integration.yml
    plugins:
      - docker-compose:
          config: ".buildkite/compose-files/sync-docker-compose.yml"
          run: sync
          workdir: /monorepo
          env:
            - BUILDKITE_TOKEN
            - PIPELINE_SLUG
            - WEB_APP_USER_EMAIL
            - WEB_APP_USER_PASSWORD
            - CI_INTEGRATIONS_FIREBASE_API_KEY
            - METRICS_PROJECT_ID
