steps:
  - label: "Run Metrics Web sync command"
    commands:
      - "cd .metrics/buildkite"
      - "curl -o ci_integrations -k https://github.com/platform-platform/monorepo/releases/download/ci_integrations-snapshot/ci_integrations_linux -L"
      - "chmod a+x ci_integrations"
      - "eval "echo \"$(sed 's/"/\\"/g' metrics_web_config.yml)\"" >> integration.yml"
      - "./ci_integrations sync --config-file integration.yml"
