steps:
  - label: "Performing sync for a project"
    key: "start"
    commands:
      - echo $$PIPELINE_SLUG
      - echo $$METRICS_PROJECT_ID

  - label: "Sync builds"
    depends_on: "start"
    commands:
      - cd .metrics/buildkite
      - curl -o ci_integrations -k https://github.com/platform-platform/monorepo/releases/download/ci_integrations-snapshot/ci_integrations_linux -L
      - chmod a+x ci_integrations
      - eval "echo \"$(sed 's/"/\\"/g' integration_config.yml)\"" >> integration.yml
      - ./ci_integrations sync --config-file integration.yml
