@startuml cli_class_diagram

package cli {
    interface BaseCli {
        + version() : Future<void>
    }

    class FlutterCli implements BaseCli {
        + version(): Future<void>
        + enableWeb(): Future<void>
        + buildWeb(String workingDir): Future<void>
    }

    class GitCli implements BaseCli {
        + clone(String repoURL, String srcPath): Future<void>
        + version(): Future<void>
    }

    class FirebaseCli implements BaseCli {
         + login(): Future<void>
         + addFirebase(String projectId, String firebaseToken): Future<void>
         + createWebApp(String projectId, String firebaseToken): Future<void>
         + initFirebaseProject(String projectId, String workingDir, String firebaseToken): Future<void>
         + clearTarget(String workingDir, String firebaseToken): Future<void>
         + applyTarget(String projectId, String workingDir, String firebaseToken): Future<void>
         + deployHosting(String workingDir, String firebaseToken): Future<void>
         + deployFirestore(String workingDir, String firebaseToken): Future<void>
         + deployFunctions(String workingDir, String firebaseToken): Future<void>
         + version(): Future<void>
    }

    class GcloudCli implements BaseCli {
        + login(): Future<void>
        + addProject(): Future<String>
        + selectProject(): Future<String>
        + setProject(): Future<void>
        + selectRegion(): Future<String>
        + addProjectApp(String region, String projectId): Future<void>
        + createDatabase(String region, String projectId): Future<void>
        + version() : Future<void>
    }

    class NpmCli implements BaseCli {
        + install(String workingDir): Future<void>
        + version(): Future<void>
    }
}

@enduml
