@startuml deploy_tool_class_diagram
left to right direction

package cli {

    package flutter {
        class FlutterCommand {
            + version(): Future<void>
            + enableWeb(): Future<void>
            + buildWeb(String workingDir): Future<void>
        }
    }

    package firebase {
        class FirebaseCommand {
            + login(): Future<String>
            + addFirebase(String projectId, String firebaseToken): Future<void>
            + createWebApp(String projectId, String firebaseToken): Future<String>
            + chooseProject(String projectId, String workingDir, String firebaseToken): Future<void>
            + clearTarget(String workingDir, String firebaseToken): Future<void>
            + applyTarget(String projectId, String workingDir, String firebaseToken): Future<void>
            + deployHosting(String workingDir, String firebaseToken): Future<void>
            + deployFirestore(String workingDir, String firebaseToken): Future<void>
            + deployFunctions(String workingDir, String firebaseToken): Future<void>
            + version(): Future<void>
        }
    }

    package gcloud {
        class GCloudCommand {
            + login(): Future<void>
            + addProject(): Future<String>
            + addProjectApp(String region, String projectId): Future<void>
            + createDatabase(String region, String projectId): Future<void>
            + version(): Future<void>
        }
    }

    package git {
        class GitCommand {
            + clone(String repoURL, String srcPath): Future<void>
            + version(): Future<void>
        }
    }

    package npm {
        class NpmCommand {
            + install(String workingDir): Future<void>
            + version(): Future<void>
        }
    }
}

package args {
    class Command {}
}

package deploy {
    class DeployCommand extends Command {
        + name : String
        + description : String
        - _firebase : FirebaseCommand
        - _gcloud : GCloudCommand
        - _git : GitCommand
        - _flutter : FlutterCommand
        - _npm : NpmCommand
        - {static} _repoURL : String
        - {static} _tempDir : String
        - {static} _webPath : String
        - {static} _firebasePath : String
        - {static} _firebaseFunctionsPath : String
        + run(): Future<void>
        - _selectRegion(): Future<String>
        - _deploy(): Future<void>
        - _cleanup(): Future<void>
    }
}

package doctor {
    class DoctorCommand extends Command {
        + name : String
        + description : String
        - _firebase : FirebaseCommand
        - _gcloud : GCloudCommand
        - _git : GitCommand
        - _flutter : FlutterCommand
        - _npm : NpmCommand
        + run(): Future<void>
    }
}

DeployCommand --> FirebaseCommand : uses
DeployCommand --> GCloudCommand : uses
DeployCommand --> GitCommand : uses
DeployCommand --> FlutterCommand : uses
DeployCommand --> NpmCommand : uses
FirebaseCommand <-- DoctorCommand : uses
GCloudCommand <-- DoctorCommand : uses
GitCommand <-- DoctorCommand : uses
FlutterCommand <-- DoctorCommand : uses
NpmCommand <-- DoctorCommand : uses

@enduml
