@startuml deploy_command_sequence_diagram

scale 1900 height

skinparam ParticipantPadding 20
skinparam BoxPadding 10

actor Bob

box "Deploy Command"
    participant CLI
    participant DeployCommand
    participant FirebaseCommand
    participant FlutterCommand
    participant GCloudCommand
    participant GitCommand
    participant NpmCommand
end box

participant gcloud

participant firebase

participant git

participant flutter

participant npm

Bob -> CLI ++ : run deploy command
CLI -> DeployCommand ++ : run()
DeployCommand -> GCloudCommand ++ : login()
GCloudCommand -> gcloud ++ : login to the google cloud
gcloud --> Bob -- : starts interactive login
GCloudCommand --

Bob -> gcloud ++ : signs in
gcloud --> DeployCommand -- : login finished

DeployCommand -> GCloudCommand ++ : addProject()
GCloudCommand --> Bob -- : asks to create new project

alt Agree to create a new project
    Bob -> GCloudCommand ++ : Y
    GCloudCommand -> gcloud ++ : create a new google cloud project
    return project has been created

else Do not agree to create a new project
    Bob -> GCloudCommand : N
    GCloudCommand -> gcloud ++ : request a list of gcloud projects
    gcloud --> Bob -- : shows all available projects
    GCloudCommand --> Bob : asks to enter the project id
    Bob -> GCloudCommand : enters the project id
end

GCloudCommand -> gcloud ++ : set gcloud config to point to a new project
return project has been set
GCloudCommand --> DeployCommand -- : projectID

DeployCommand --> Bob : asks to enter the region
Bob -> DeployCommand : enters the region
DeployCommand -> GCloudCommand ++ : addProjectApp(region, projectID)
GCloudCommand --> Bob -- : asks to add a project app

alt Agree to add the project app
    Bob -> GCloudCommand ++ : Y
    GCloudCommand -> gcloud ++ : create project app
    gcloud --> DeployCommand -- : project app has been created
    GCloudCommand --
else Do not agree to add the project app
    Bob -> GCloudCommand ++ : N
    GCloudCommand --> DeployCommand -- : skipped
end

DeployCommand -> GCloudCommand ++ : createDatabase(region, projectID)
GCloudCommand --> Bob -- : asks to add a project database

alt Agree to add the project database
    Bob -> GCloudCommand ++ : Y
    GCloudCommand -> gcloud ++ : enable firestore API
    return firestore API has been enabled
    GCloudCommand -> gcloud ++ : create a database
    gcloud --> DeployCommand -- : database has been created
    GCloudCommand --
else Do not agree to add the project database
    Bob -> GCloudCommand ++ : N
    GCloudCommand --> DeployCommand -- : skipped
end

DeployCommand -> FirebaseCommand ++ : login()
FirebaseCommand -> firebase ++ : login to the firebase
firebase --> Bob -- : starts interactive login
FirebaseCommand --

Bob -> firebase ++ : signs in
firebase --> Bob -- : firebase token
Bob -> DeployCommand : enters firebase token

DeployCommand -> FirebaseCommand ++ : addFirebase(projectID, firebaseToken)
FirebaseCommand --> Bob -- : asks to add a firebase capabilities

alt Agree to add the firebase capabilities
    Bob -> FirebaseCommand ++ : Y
    FirebaseCommand -> firebase ++ : add firebase capabilities to the cloud project
    firebase --> DeployCommand -- : firebase capabilities has been added
    FirebaseCommand --
else Do not agree to add the firebase capabilities
    Bob -> FirebaseCommand ++ : N
    FirebaseCommand --> DeployCommand -- : skipped
end

DeployCommand -> FirebaseCommand ++ : createWebApp(projectID, firebaseToken)
FirebaseCommand --> Bob -- : asks to add a web app

alt Agree to add the web app
    Bob -> FirebaseCommand ++ : Y
    FirebaseCommand -> firebase ++ : create web app
    firebase --> DeployCommand -- : web app has been created
    FirebaseCommand --
else Do not agree to add the web app
    Bob -> FirebaseCommand ++ : N
    FirebaseCommand -> DeployCommand -- : skipped
end

DeployCommand -> GitCommand ++ : clone(repoURL, tempDir)
GitCommand -> git ++ : clone the source project
git --> DeployCommand -- : project has been cloned
GitCommand --

DeployCommand -> FirebaseCommand ++ : initFirebaseProject(projectId, webPath, firebaseToken)
FirebaseCommand -> firebase ++ : choose the firebase project
firebase --> DeployCommand -- : project has been chosen
FirebaseCommand --

DeployCommand -> FlutterCommand ++ : buildWeb(webPath)
FlutterCommand -> flutter ++ : build the source project
flutter --> DeployCommand -- : flutter web app has been built
FlutterCommand --

DeployCommand -> FirebaseCommand ++ : clearTarget(webPath, firebaseToken)
FirebaseCommand -> firebase ++ : clear the firebase target
firebase --> DeployCommand -- : firebase target has been cleared
FirebaseCommand --

DeployCommand -> FirebaseCommand ++ : applyTarget(projectId, webPath, firebaseToken)
FirebaseCommand -> firebase ++ : apply the firebase target
firebase --> DeployCommand -- : firebase target has been applied
FirebaseCommand --

DeployCommand --> Bob : firebase analytics warning
Bob -> DeployCommand : enters any key

DeployCommand -> FirebaseCommand ++ : deployHosting(webPath, firebaseToken)
FirebaseCommand -> firebase ++ : deploy the web application to the hosting
firebase --> DeployCommand -- : application has been deployed
FirebaseCommand --

DeployCommand -> FirebaseCommand ++ : initFirebaseProject(projectId, firebasePath, firebaseToken)
FirebaseCommand -> firebase ++ : choose the firebase project
firebase --> DeployCommand -- : project has been chosen
FirebaseCommand --

DeployCommand -> NpmCommand ++ : install(firebasePath)
NpmCommand -> npm ++ : install npm dependencies into the firebase folder
npm --> DeployCommand -- : dependencies have been installed
NpmCommand --

DeployCommand -> FirebaseCommand ++ : deployFirestore(firebasePath, firebaseToken)
FirebaseCommand -> firebase ++ : deploy the firestore settings to firebase
firebase --> DeployCommand -- : firestore settings have been deployed
FirebaseCommand --

DeployCommand --> Bob : asks to enable a Blaze billing account for functions deployment

alt Agree to enable the Blaze billing account
    Bob -> DeployCommand : Y

    DeployCommand -> NpmCommand ++ : install(firebaseFunctionsPath)
    NpmCommand -> npm ++ : install npm dependencies into the functions folder
    npm --> DeployCommand -- : dependencies have been installed
    NpmCommand --

    DeployCommand -> FirebaseCommand ++ : deployFunctions(firebasePath, firebaseToken)
    FirebaseCommand -> firebase ++ : deploy the functions to firebase
    firebase --> DeployCommand -- : functions have been deployed
    FirebaseCommand --
else Do not agree to enable the Blaze billing account
    Bob -> DeployCommand : N
    DeployCommand -> DeployCommand : skipped
end

DeployCommand -> DeployCommand : clean up the source directory
DeployCommand --> CLI --: deploy finished
CLI --> Bob -- : terminate
CLI --

@enduml
