@startuml deploy_tool_class_diagram
left to right direction

package utils {
    class FileHelper {
        + deleteDirectory(Directory directory) : Future<void>
    }
    class PromptWrapper {
        + prompt(String text, {Stream<List<int>> stdin}) : Future<String>
        + promptConfirm(String text, {Stream<List<int>> stdin}) : Future<bool>
        + promptTerminate() : Future<void>
    }
    class PromptUtil {
        - {static} _promptWrapper : PromptWrapper
        + {static} init(PromptWrapper promptWrapper) : void
        + {static} prompt(String text, {Stream<List<int>> stdin}) : Future<String>
        + {static} promptConfirm(String text, {Stream<List<int>> stdin}) : Future<bool>
        + {static} promptTerminate() : Future<void>
    }
}

package cli {
    package flutter {
        class FlutterCommand {
            + version(): Future<void>
            + enableWeb(): Future<void>
            + buildWeb(String workingDir): Future<void>
        }
    }

    package firebase {
        class FirebaseCommand {
            + login(): Future<String>
            + addFirebase(String projectId, String firebaseToken): Future<void>
            + createWebApp(String projectId, String firebaseToken): Future<String>
            + chooseProject(String projectId, String workingDir, String firebaseToken): Future<void>
            + clearTarget(String workingDir, String firebaseToken): Future<void>
            + applyTarget(String projectId, String workingDir, String firebaseToken): Future<void>
            + deployHosting(String workingDir, String firebaseToken): Future<void>
            + deployFirestore(String workingDir, String firebaseToken): Future<void>
            + deployFunctions(String workingDir, String firebaseToken): Future<void>
            + version(): Future<void>
        }
    }

    package npm {
        class NpmCommand {
            + install(String workingDir): Future<void>
            + version(): Future<void>
        }
    }

    package gcloud {
        class GCloudCommand {
            + login(): Future<void>
            + addProject(): Future<String>
            + addProjectApp(String region, String projectId): Future<void>
            + createDatabase(String region, String projectId): Future<void>
            + version(): Future<void>
        }
    }

    package git {
        class GitCommand {
            + clone(String repoURL, String srcPath): Future<void>
            + version(): Future<void>
        }
    }
}

package args {
    class CommandRunner{}
    class Command {}
}

package deploy {
    class DeployCommand {
        + name : String
        + description : String
        - _firebase : FirebaseCommand
        - _gcloud : GCloudCommand
        - _git : GitCommand
        - _flutter : FlutterCommand
        - _npm : NpmCommand
        - _fileHelper : FileHelper
        + run(): Future<void>
        - _selectRegion(): Future<String>
        - _deploy(): Future<void>
    }
}

package doctor {
    class DoctorCommand {
        + name : String
        + description : String
        - _firebase : FirebaseCommand
        - _gcloud : GCloudCommand
        - _git : GitCommand
        - _flutter : FlutterCommand
        - _npm : NpmCommand
        + run(): Future<void>
    }
}

package runner {
    class MetricsCommandRunner extends CommandRunner {
    }
}

package constants {
    class ConfigConstants{
        + {static} repoUrl : String
        + {static} tempDir : String
        + {static} webPath : String
        + {static} firebasePath : String
        + {static} firebaseFunctionsPath : String
    }
}

package strings {
    class PromptStrings{
        + {static} enableAnalytics : String
        + {static} enableBillingAccount : String
        + {static} selectRegion : String
        + {static} firebaseToken : String
        + {static} addFirebaseCapabilities : String
        + {static} createProjectDatabase : String
        + {static} addProjectApp : String
        + {static} addWebApp : String
        + {static} createNewProject : String
        + {static} selectProjectId : String
    }
}

DoctorCommand --|> Command
DeployCommand -down-|> Command

MetricsCommandRunner --> DeployCommand : uses
MetricsCommandRunner --> DoctorCommand : uses

DeployCommand --> GCloudCommand: uses
DeployCommand --> FirebaseCommand : uses
DeployCommand --> GitCommand : uses
DeployCommand --> FlutterCommand : uses
DeployCommand --> NpmCommand : uses
DeployCommand -right-> ConfigConstants : uses

FirebaseCommand <-- DoctorCommand : uses
GCloudCommand <-- DoctorCommand : uses
GitCommand <-- DoctorCommand : uses
FlutterCommand <-- DoctorCommand : uses
NpmCommand <-- DoctorCommand : uses

PromptUtil -down-> PromptWrapper : uses
PromptUtil <-down- DeployCommand : uses
PromptUtil <-- GCloudCommand : uses
PromptUtil <-- FirebaseCommand : uses

GCloudCommand -left-> PromptStrings : uses
FirebaseCommand -left-> PromptStrings : uses
DeployCommand -left-> PromptStrings : uses

FileHelper <-- DeployCommand : uses

@enduml
