@startuml deploy_command_activity_diagram

(*) --> "User execute the Deploy command"
--> "Gcloud login"
--> "Gcloud create project"
--> "Gcloud create project app"
--> "Gcloud create database"
--> "Firebase login"
--> "Add firebase"
--> "Create web app"
--> "Insltall Npm dependencies"
--> "Deploy firebase rules and functions"
--> "Build web app"
--> "Deploying the web app to the hosting"
--> "Cleanup resources"
--> (*)

@enduml
