@startuml deploy_command_class_diagram

package deploy {
    package command {
     class DeployCommand {
      deployService : DeployService
      + run() : Future<void>
     }
    }

    package service {
        interface DeployService {
            + initGcloud() : Future<String>
            + initFirebase() : Future<String>
            + clone() : Future<void>
            + build() : Future<void>
            + deploy() : Future<void>
            + cleanup() : Future<void>
        }

        class DeployCliService implements DeployService {
            - _firebaseCli : FirebaseCli
            - _gcloudCli : GcloudCli
            - _gitCli : GitCli
            - _flutterCli : FlutterCli
            - _npmCli : NpmCli
            - _fileHelper : FileHelper
            + initGcloud() : Future<String>
            + initFirebase() : Future<String>
            + clone() : Future<void>
            + build() : Future<void>
            + deploy() : Future<void>
            + cleanup() : Future<void>
        }
    }
}

DeployCommand --> DeployService : uses

@enduml
