@startuml deploy_command_sequence_diagram

scale 1900 height

skinparam ParticipantPadding 20
skinparam BoxPadding 10

actor Bob

box Deploy Command
participant MetricsCliRunner
participant DeployCommand
participant Deployer
participant GCloudService
participant FirebaseService
participant GitService
participant NpmService
participant FlutterService
end box


participant FileHelper

Bob -> MetricsCliRunner ++ : run deploy command
MetricsCliRunner -> DeployCommand ++ : run()
DeployCommand -> Deployer ++ : deploy()
Deployer -> GCloudService ++ : login()

GCloudService --> Bob : start interactive login
Bob -> GCloudService : signs in
GCloudService --> Deployer : sign in finished
GCloudService --

Deployer -> GCloudService ++ : createProject()

GCloudService --> Bob : asks to enter the regionId
Bob -> GCloudService : enters the regionId

GCloudService --> Deployer -- : gcloud project has been created

Deployer -> FirebaseService ++ : login()
FirebaseService --> Bob : starts interactive login
Bob -> FirebaseService : signs in
FirebaseService --> Deployer -- : sign in finished

Deployer -> FirebaseService ++ : addProject(projectId)

FirebaseService --> Deployer -- : firebase project has been added

Deployer -> GitService ++ : checkout(repoUrl, srcPath)
GitService --> Deployer : checkout finished
GitService --


Deployer -> NpmService ++ : installDependencies(firebasePath)
NpmService --> Deployer : dependencies have been installed
NpmService --

Deployer -> NpmService ++ : installDependencies(firebaseFunctionsPath)
NpmService --> Deployer : dependencies have been installed
NpmService --

Deployer -> FirebaseService ++ : deployFirestore(firestorePath)

FirebaseService --> Bob : Blaze billing account warning
Bob -> FirebaseService : enters any key

FirebaseService --> Bob : firebase analytics warning
Bob -> FirebaseService : enters any key

FirebaseService --> Deployer -- : firestore has been deployed


Deployer -> FlutterService ++ : build()
FlutterService -> Deployer : build finished
FlutterService --

Deployer -> FirebaseService ++ : deployHosting(appPath)
FirebaseService -> Deployer : deploy finished
FirebaseService --

Deployer -> FileHelper ++: deleteDirectory(directory)
FileHelper --> Deployer --: directory has been cleaned up
Deployer --> DeployCommand --: deploy finished
DeployCommand --> MetricsCliRunner --: command finished
MetricsCliRunner --> Bob -- : terminate
MetricsCliRunner --

@enduml
