@startuml doctor_command_class_diagram

package doctor {
    package command {
        class DoctorCommand {
         - doctorService : DoctorService
         + run() : Future<void>
        }
    }

    package service {
        interface DoctorService {
            + version() : Future<void>
        }

        class DoctorCliService implements DoctorService {
            - _firebaseCli : FirebaseCli
            - _gcloudCli : GcloudCli
            - _flutterCli : FlutterCli
            - _gitCli : GitCli
            - _npmCli : NpmCli
            + version() : Future<void>
        }
    }
}

DoctorCommand --> DoctorService : uses

@enduml
