@startuml doctor_activity_diagram

(*) --> “User executes the Doctor command”
--> “The command shows firebase version”
--> “The command shows gcloud version”
--> “The command shows flutter version”
--> “The command shows npm version”
--> “The command shows git version”
--> (*)

@enduml
