@startuml doctor_command_class_diagram

package doctor {
    package command {
        class DoctorCommand {
         - doctor : Doctor
         + run() : Future<void>
        }
    }

    class Doctor {
            - _firebaseService : FirebaseService
            - _gcloudService : GcloudService
            - _flutterService : FlutterService
            - _gitService : GitService
            - _npmService : NpmService
            + version() : Future<void>
    }
}

package cli {
    class FirebaseService {}
    class GcloudService {}
    class FlutterService {}
    class GitService {}
    class NpmService {}
}

DoctorCommand --> Doctor : uses
Doctor --> FirebaseService : uses
Doctor --> GcloudService : uses
Doctor --> FlutterService : uses
Doctor --> GitService : uses
Doctor --> NpmService : uses
@enduml