@startuml doctor_command_sequence_diagram

skinparam ParticipantPadding 20
skinparam BoxPadding 10

actor Bob

box Doctor Command
participant CLI
participant DoctorCommand
participant Doctor

participant FlutterService
participant FirebaseService
participant GCloudService
participant GitService
participant NpmService

participant FlutterCli
participant FirebaseCli
participant GCloudCli
participant GitCli
participant NpmCli

end box

participant flutter
participant firebase
participant gcloud
participant git
participant npm


Bob -> CLI ++ : run doctor command
CLI -> DoctorCommand ++ : run()
DoctorCommand -> Doctor ++ : version()

Doctor -> FlutterService ++ : version()
FlutterService -> FlutterCli ++ : version()
FlutterCli -> flutter ++ : request flutter version
flutter --> Bob -- : print Flutter version
FlutterService --
FlutterCli --

Doctor -> FirebaseService ++ : version()
FirebaseService -> FirebaseCli ++ : version()
FirebaseCli -> firebase ++ : request firebase CLI version
firebase --> Bob -- : print Firebase version
FirebaseService --
FirebaseCli --

Doctor -> GCloudService ++ : version()
GCloudService -> GCloudCli ++ : version()
GCloudCli -> gcloud ++ : request gcloud CLI version
gcloud --> Bob -- : print GCloud version
GCloudService --
GCloudCli --

Doctor -> GitService ++ : version()
GitService -> GitCli ++ : version()
GitCli -> git ++ : request git CLI version
git --> Bob -- : print Git version
GitService --
GitCli --

Doctor -> NpmService ++ : version()
NpmService -> NpmCli ++ : version()
NpmCli -> npm ++ : request npm CLI version
npm --> Bob -- : print Npm version
NpmService --
NpmCli --

Doctor --> DoctorCommand -- : versions have been printed
DoctorCommand --> CLI -- : doctor finished

CLI --> Bob -- : terminate

@enduml
