@startuml doctor_command_sequence_diagram

skinparam ParticipantPadding 20
skinparam BoxPadding 10

actor Bob

box Doctor Command
participant MetricsCliRunner
participant DoctorCommand
participant DoctorFactory
participant Doctor

participant FlutterService
participant FirebaseService
participant GCloudService
participant GitService
participant NpmService
participant SentryService

end box

Bob -> MetricsCliRunner ++ : run doctor command
MetricsCliRunner -> DoctorCommand ++ : run()
DoctorCommand -> DoctorFactory ++ : create()
return Doctor instance
DoctorCommand -> Doctor ++ : checkVersions()

Doctor -> FlutterService ++ : version()
FlutterService --> Bob -- : print Flutter version

Doctor -> FirebaseService ++ : version()
FirebaseService --> Bob -- : print Firebase version

Doctor -> GCloudService ++ : version()
GCloudService --> Bob -- : print GCloud version

Doctor -> GitService ++ : version()
GitService --> Bob -- : print Git version

Doctor -> NpmService ++ : version()
NpmService --> Bob -- : print Npm version

Doctor -> SentryService ++ : version()
SentryService --> Bob -- : print Sentry version

Doctor --> DoctorCommand -- : doctor finished
DoctorCommand --> MetricsCliRunner -- : command finished

MetricsCliRunner --> Bob -- : terminate

@enduml
