@startuml metrics_cli_runner_class_diagram

package args {
    class CommandRunner{}
    class Command {
        + name: String
        + description: String
        + run(): Future<void>
    }
}

package cli {
    package doctor {
        package factory as doctor.factory {
            class DoctorFactory {
            - _servicesFactory: ServicesFactory
            + create(): Doctor
            }
        }
    }

    package runner {
        class MetricsCliRunner {}
    }

    package command {
        class DeployCommand {
            + deployerFactory: DeployerFactory
        }

        class DoctorCommand {
            + doctorFactory: DoctorFactory
        }
    }

    package deploy {
        package factory as deploy.factory{
            class DeployerFactory {
                - _servicesFactory: ServicesFactory
                + create(): Deployer
            }
        }
    }
}

MetricsCliRunner --> DoctorCommand: uses
MetricsCliRunner --> DeployCommand: uses
DeployCommand -left-> DeployerFactory: uses
DoctorCommand -right-> DoctorFactory: uses

DeployCommand --|> Command
DoctorCommand --|> Command

MetricsCliRunner --|> CommandRunner


@enduml
