@startuml metrics_cli_runner_class_diagram

package args {
    class CommandRunner{}
    class Command {}
}

package cli {
    package doctor {
        package factory as doctor.factory {
            class DoctorFactory {}
        }
    }

    package runner {
        class MetricsCliRunner {}
    }

    package command {
        class DeployCommand {}
        class DoctorCommand {}
    }

    package deploy {
        package factory as deploy.factory{
            class DeployerFactory {}
        }
    }
}

MetricsCliRunner --> DoctorCommand : uses
MetricsCliRunner --> DeployCommand : uses
DeployCommand -left-> DeployerFactory : uses
DoctorCommand -right-> DoctorFactory : uses

DeployCommand --|> Command
DoctorCommand --|> Command

MetricsCliRunner --|> CommandRunner


@enduml
