@startuml prompt_class_diagram

 package prompt {
    package writer {
        class PromptWriter {
            + prompt(String text, {Stream<List<int>> stdin}) : Future<String>
            + promptConfirm(String text, {Stream<List<int>> stdin}) : Future<bool>
            + promptTerminate() : Future<void>
        }
    }

    package strings {
        class PromptStrings{}
    }

    class PromptHelper {
        - {static} _promptWrapper : PromptWrapper
        + {static} init(PromptWrapper promptWrapper) : void
        + {static} prompt(String text, {Stream<List<int>> stdin}) : Future<String>
        + {static} promptConfirm(String text, {Stream<List<int>> stdin}) : Future<bool>
        + {static} promptTerminate() : Future<void>
    }
}

PromptHelper --> PromptWriter : uses

@enduml
