@startuml prompt_class_diagram

package prompter {
    package writer {
        interface PromptWriter {
            + info(String text) : void
            + prompt(String text) : String
            + promptConfirm(String text, String confirmInput) : bool
        }

        class IOPromptWriter implements PromptWriter {
            - _stdin : Stdin
            - _stdout : Stdout
        }
    }

    class Prompter {
        - _promptWriter : PromptWriter
        + info(String text) : void
        + prompt(String text) : String
        + promptConfirm(String text, {String confirmInput}) : bool
    }
}

package cool.adapter {
    class CoolCliServiceAdapter {}
}

Prompter --> PromptWriter : uses

CoolCliServiceAdapter --> Prompter : uses

@enduml
