@startuml prompt_class_diagram

package prompt {
    package writer {
        interface PromptWriter {
            + prompt(String text) : Future<String>
            + promptConfirm(String text) : Future<bool>
            + promptTerminate() : Future<void>
        }

        class IOPromptWriter implements PromptWriter{
            - _stdin : Stream<List<int>>
            - _stdout : Sink<List<int>>
        }
    }

    package strings {
        class PromptStrings{}
    }

    class Prompter {
        - _promptWrapper : PromptWrapper
        + prompt(String text) : Future<String>
        + promptConfirm(String text) : Future<bool>
        + promptTerminate() : Future<void>
    }
}

package cool.adapter {
    class CoolCliServiceAdapter {

    }
}

Prompter --> PromptWriter : uses

CoolCliServiceAdapter --> Prompter : uses
CoolCliServiceAdapter --> PromptStrings : uses

@enduml
