name: Metrics CLI Actions

on:
  push:
    branches: master
    paths:
      - metrics/cli/**

jobs:
  cli-actions:
    name: CLI Actions
    runs-on: macOS-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          ref: ${{ github.ref }}

      - uses: cedx/setup-dart@v2
        with:
          release-channel: beta
          version: 2.12.0-133.2.beta

      - name: Get dependencies
        run: pub get
        working-directory: metrics/cli/

      - name: Dart analyze
        run: dartanalyzer . --fatal-infos --fatal-warnings
        working-directory: metrics/cli/

      - name: Run tests
        run: pub run test
        working-directory: metrics/cli/
        
  send-notification:
    name: Send notification to Slack
    runs-on: ubuntu-latest
    needs: [ cli-actions ]
    if: ${{ always() }}
    steps:
      - name: Send notification to Slack
        uses: peter-evans/repository-dispatch@v1
        if: needs.cli-actions.result == 'failure' || needs.cli-actions.result == 'cancelled'
        with:
          token: ${{ secrets.ACTIONS_TOKEN }}
          repository: ${{ github.repository }}
          event-type: send_slack_notification
          client-payload: '{"workflow_name": "${{ github.workflow }}", "run_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"}'
