name: Firebase Actions

on:
  push:
    branches: master
    paths:
      - metrics/firebase/**

jobs:
  metrics-actions:
    name: Firebase actions
    runs-on: macOS-latest
    timeout-minutes: 60
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      PROJECT_PATH: metrics/firebase/

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          ref: ${{ github.ref }}

      - name: Install Firebase CLI
        run: curl -sL https://firebase.tools | bash

      - name: Install NPM dependencies
        run: npm install && npm install --prefix functions
        working-directory: metrics/firebase/

      - uses: cedx/setup-dart@v2
        with:
          release-channel: beta
          version: 2.12.0-133.2.beta

      - name: Get dependencies
        run: pub get
        working-directory: metrics/firebase/functions/

      - name: Dart analyze
        run: dartanalyzer . --fatal-infos --fatal-warnings
        working-directory: metrics/firebase/functions/

      - name: Run Cloud Functions tests
        run: pub run test
        working-directory: metrics/firebase/functions/

      - name: Deploy Cloud Functions
        run: firebase use default && firebase deploy --only functions
        working-directory: metrics/firebase/

      - name: Run Firestore security rules tests
        run: firebase emulators:exec --only firestore "npm run test"
        working-directory: metrics/firebase/

      - name: Deploy Firestore security rules
        run: firebase use default && firebase deploy --only firestore:rules
        working-directory: metrics/firebase/
