name: Firebase Actions

on:
  pull_request:
    paths:
      - metrics/firebase/**
  push:
    branches: master
    paths:
      - metrics/firebase/**


jobs:
  metrics-actions:
    name: Firebase actions
    runs-on: macOS-latest
    timeout-minutes: 60
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      PROJECT_PATH: metrics/firebase/

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          ref: ${{ github.ref }}

      - name: Install Firebase CLI
        run: curl -sL https://firebase.tools | bash

      - name: NPM install
        run: npm install
        working-directory: metrics/firebase/

      - name: Run Firestore security rules tests
        run: firebase emulators:exec --only firestore "npm run test"
        working-directory: metrics/firebase/

      - name: Deploy Firestore security rules
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: firebase use default && firebase deploy --only firestore:rules
        working-directory: metrics/firebase/
