name: shell_words
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  unicode: ^0.2.2

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.12.0
